export const CLICKHOUSE_CLIENT = 'CLICKHOUSE_CLIENT';

export const CLICKHOUSE_TABLES = {
	FACT_DSP_COMPREHENSIVE_REPORT: 'fact_dsp_comprehensive_report',
	FACT_SALES_REPORT: 'fact_sales_report',
	SALES_ISRC_MONTHLY: 'sales_dsp_monthly_cube_v2',
	SALES_DSP_MONTHLY: 'sales_dsp_monthly_cube_v2',
	TRENDS_ISRC_DAILY_CUBE: 'trends_isrc_daily_cube',
	TRENDS_DSP_DAILY_CUBE: 'trends_dsp_daily_cube',
	PG_TRACKS_SYNC: 'pg_tracks_sync',
	PG_ASSET_OWNERSHIP_SYNC: 'pg_asset_ownership_sync',
	PG_DSPS_SYNC: 'pg_dsps_sync',
	DSPS_REPORT: 'dsps_report',
	DSP_REPORT_STATS: 'dsp_report_stats',
	TRENDS_DSP_MONTHLY: 'trends_dsp_monthly_cube',
	SALES_TER_MONTHLY: 'sales_ter_monthly_cube_v2',
	SALES_EXPORT_MONTHLY: 'sales_export_monthly_cube',
	TRENDS_TER_MONTHLY: 'trends_ter_monthly_cube',
	TRENDS_TER_DAILY_CUBE: 'trends_ter_daily_cube',
	IMPORT_JOBS: 'import_jobs',
	REPORT_SOURCE_CONFIGS: 'report_source_configs',
	EXCHANGE_RATES: 'exchange_rates',
	FTP_EXCLUDE_PATTERNS: 'ftp_exclude_patterns',
	FTP_DSP_PARSER_CONFIGS: 'ftp_dsp_parser_configs',
	FTP_PARSER_FIELD_MAPPINGS: 'ftp_parser_field_mappings',
	FTP_PARSER_CATALOG: 'ftp_parser_catalog',
	FTP_REPORT_FILE_CATALOG: 'ftp_report_file_catalog',
	FTP_REPORT_FILE_RULES: 'ftp_report_file_rules',
	FTP_REPORT_FILE_SCAN_RUNS: 'ftp_report_file_scan_runs',
	FTP_REPORT_FILE_DISCOVERY_CONFIG: 'ftp_report_file_discovery_config',
	FTP_REPORT_FILE_DISCOVERY_CHECKPOINTS:
		'ftp_report_file_discovery_checkpoints',
	FTP_REPORT_FILE_PERIOD_OBSERVATIONS: 'ftp_report_file_period_observations',
	FTP_REPORT_SAMPLE_TASKS: 'ftp_report_sample_tasks',
	METADATA_ENRICHMENT_LOG: 'metadata_enrichment_log',
	ANALYTICS_SOURCE_TYPE_CONFIGS: 'analytics_source_type_configs',
} as const;
