[drive]
type = drive
scope = drive
token = ''

[gcs]
type = google cloud storage
service_account_file = ./credential.json
location = asia
bucket_policy_only = true

[r2]
# type, provider, access_key_id, secret_access_key, endpoint
# have been moved to environment variables and injected automatically.
# (See database.backup.service.ts)
