[drive]
type = drive
scope = drive
token = ''

[gcs]
type = google cloud storage
service_account_file = ./credential.json
location = asia
bucket_policy_only = true

[r2]
type = s3
provider = Cloudflare
access_key_id = 
secret_access_key = 
endpoint = 
