services:
    app-dev:
        # image: ag-music-server/dev:latest
        image: ag-music-server/dev:${TAG:-latest}
        build: .
        # pull the port number from $PORT for both host and container
        ports:
            - '${HOST_PORT:-4041}:${APP_PORT}'
        env_file:
            - .env
        environment:
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
            - APP_ROLE=api
        command: yarn start:prod
        restart: unless-stopped
        volumes:
            - ./proto:/app/proto:ro
            - ./credential.json:/app/credential.json:ro
            - ./secrets:/app/secrets:ro
            - ./database.rclone.conf:/app/database.rclone.conf:ro
            - ./release_parsed:${RELEASE_PARSED_DIR}
        mem_limit: 1500m
        cpus: 1.5
        depends_on:
            - app-dev-worker

    app-dev-worker:
        image: ag-music-server/dev:${TAG:-latest}
        env_file:
            - .env
        environment:
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
            - APP_ROLE=worker
        command: yarn start:prod
        restart: unless-stopped
        volumes:
            - ./proto:/app/proto:ro
            - ./credential.json:/app/credential.json:ro
            - ./secrets:/app/secrets:ro
            - ./database.rclone.conf:/app/database.rclone.conf:ro
            - ./release_parsed:${RELEASE_PARSED_DIR}
        mem_limit: 1g
        cpus: 0.5
