services:
    app-dev:
        # image: ag-music-server/dev:latest
        image: ag-music-server/dev:${TAG:-latest}
        build: .
        # pull the port number from $PORT for both host and container
        ports:
            - '${HOST_PORT:-4041}:${APP_PORT}'
        env_file:
            - .env
        environment:
            - TZ=${TZ:-Asia/Ho_Chi_Minh}
        command: yarn start:prod
        restart: unless-stopped
        volumes:
            - ./credential.json:/app/credential.json:ro
            - ./secrets:/app/secrets:ro
            - ./database.rclone.conf:/app/database.rclone.conf:ro
            - ./scripts/script.backup.sh:/app/scripts/script.backup.sh

        mem_limit: 2g # Set max memory to 2 GB
        cpus: 2 # Set max CPU to 2 CPU core
