export enum DistributionV2ExecutionType {
	INITIAL = 'INITIAL',
	UPDATE = 'UPDATE',
	TAKEDOWN = 'TAKEDOWN',
}

export enum DistributionV2Status {
	SUBMITTED = 'SUBMITTED',
	VALIDATING = 'VALIDATING',
	WAITING_REVIEW = 'WAITING_REVIEW',
	PROVISIONING_IDS = 'PROVISIONING_IDS',
	BUILDING_PACKAGE = 'BUILDING_PACKAGE',
	DISTRIBUTING = 'DISTRIBUTING',
	ACTION_REQUIRED = 'ACTION_REQUIRED',
	DISTRIBUTED = 'DISTRIBUTED',
	PARTIALLY_DISTRIBUTED = 'PARTIALLY_DISTRIBUTED',
	FAILED = 'FAILED',
	TAKEN_DOWN = 'TAKEN_DOWN',
}

export enum DistributionV2ChannelRoute {
	DIRECT = 'DIRECT',
	CI = 'CI',
	STATE51 = 'STATE51',
}

export enum DistributionV2ChannelStatus {
	PENDING = 'PENDING',
	PROCESSING = 'PROCESSING',
	WAITING_EXTERNAL = 'WAITING_EXTERNAL',
	WAITING_BATCH = 'WAITING_BATCH',
	LIVE = 'LIVE',
	ISSUES = 'ISSUES',
	TAKEN_DOWN = 'TAKEN_DOWN',
	SKIPPED = 'SKIPPED',
}

export enum DistributionV2WaitReason {
	PARTNER = 'PARTNER',
	CI_IMPORT = 'CI_IMPORT',
	EXPORT = 'EXPORT',
	GO_LIVE = 'GO_LIVE',
	TAKEDOWN = 'TAKEDOWN',
}

export enum DistributionV2StepStatus {
	PENDING = 'PENDING',
	PROCESSING = 'PROCESSING',
	WAITING = 'WAITING',
	DONE = 'DONE',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

export enum DistributionV2BatchType {
	CI_EXPORT = 'CI_EXPORT',
	STATE51_EMAIL = 'STATE51_EMAIL',
}

export enum DistributionV2BatchStatus {
	OPEN = 'OPEN',
	PROCESSING = 'PROCESSING',
	SENT = 'SENT',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

export enum DistributionV2ExternalOperationStatus {
	PENDING = 'PENDING',
	SUCCEEDED = 'SUCCEEDED',
	FAILED = 'FAILED',
	UNKNOWN = 'UNKNOWN',
}

export enum DistributionV2IssueStatus {
	OPEN = 'OPEN',
	RESOLVED = 'RESOLVED',
	DISMISSED = 'DISMISSED',
}
