import { Injectable, Logger } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import * as fs from 'fs';
import * as os from 'os';
import * as path from 'path';
import { Repository } from 'typeorm';

import { genBatchId } from '../../../../utils/util';
import { BucketService2 } from '../../../bucket2/services/bucket2.service';
import { DspRoutingConfigsService } from '../../../distribution/dsp-routing/services/dsp-routing-config.service';
import { ErnService2 } from '../../../ern2/services/ern.service';
import { PackageBuilder } from '../../domain/ports/package-builder.port';
import { IdempotencyKey } from '../../domain/value-objects/idempotency-key.vo';
import { PackagePath } from '../../domain/value-objects/package-path.vo';
import { ReleaseSnapshotOrmEntity } from '../persistence/release-snapshot.orm-entity';
import {
	mapSnapshotToErnInput,
	ReleaseSnapshotPayload,
} from './ddex-data-mapper';
import { parseProcessCode } from './process-code-resolver';

/**
 * DdexXmlPackageBuilder — real adapter implementing PackageBuilder port.
 *
 * Flow: load snapshot → resolve config → map → generate XML → write files → return PackagePath.
 *
 * Builds DDEX package on LOCAL FILESYSTEM (giống v3):
 *   $RELEASE_PARSED_DIR/{batchId}/{releaseReference}/
 *     resources/ (audio files + cover art — downloaded from BucketService2)
 *     release.xml (ERN XML — generated by ErnService2)
 *     BatchComplete_*.xml (manifest — CI aggregator only)
 *
 * Idempotency: bảo đảm chính ở APPLICATION layer — BuildPackageRunner skip build nếu
 * `dist.packageUri` đã set (không gọi lại adapter). Bên trong adapter, batchId sinh mới mỗi lần
 * (genBatchId theo timestamp — giữ đúng convention folder CI aggregator quét), nên check
 * `fs.existsSync` bên dưới CHỈ bắt trường hợp cùng batchId hiếm gặp, KHÔNG phải lớp idempotent chính.
 */
@Injectable()
export class DdexXmlPackageBuilder implements PackageBuilder {
	private readonly logger = new Logger(DdexXmlPackageBuilder.name);
	private readonly baseDir: string;

	constructor(
		@InjectRepository(ReleaseSnapshotOrmEntity)
		private readonly snapshotRepo: Repository<ReleaseSnapshotOrmEntity>,
		private readonly ernService: ErnService2,
		private readonly bucketService: BucketService2,
		private readonly dspRoutingService: DspRoutingConfigsService,
	) {
		this.baseDir =
			process.env.RELEASE_PARSED_DIR || path.resolve('release_parsed');
	}

	async build(input: {
		snapshotId: string;
		processCode: string;
		key: IdempotencyKey;
	}): Promise<PackagePath> {
		const { snapshotId, processCode, key } = input;
		this.logger.log(
			`[build] snapshotId=${snapshotId} processCode=${processCode} key=${key.value}`,
		);

		// 1. Parse processCode → build config
		const buildConfig = parseProcessCode(processCode);

		// 2. Load snapshot
		const snapshot = await this.snapshotRepo.findOne({
			where: { id: snapshotId },
		});
		if (!snapshot) {
			throw new Error(
				`DdexXmlPackageBuilder: snapshot not found: ${snapshotId}`,
			);
		}
		const payload = snapshot.payload as unknown as ReleaseSnapshotPayload;
		const releaseReference = payload.upc ?? snapshotId;

		// 3. Idempotency: check if output folder already exists
		const batchId = this.deriveBatchId(key);
		const outputDir = path.join(this.baseDir, batchId, releaseReference);
		if (fs.existsSync(outputDir)) {
			this.logger.log(
				`[build] Idempotent hit — folder exists: ${outputDir}`,
			);
			return PackagePath.create(
				'local',
				`${batchId}/${releaseReference}`,
			);
		}

		// 4. Resolve delivery config (ernVersion, sender, recipient).
		// Aggregator (CI): dspRoute = aggregator code → recipient = CI, sender = AMG.
		// Direct: dspRoute = dspCode → recipient = DSP, sender = AMG.
		const routingConfig = buildConfig.isAggregator
			? await this.dspRoutingService.resolveAggregatorDeliveryConfig(
					buildConfig.dspRoute,
				)
			: await this.dspRoutingService.resolveFullDeliveryConfig(
					buildConfig.dspRoute,
				);

		// Create temp dir for bucket downloads (cleaned in finally)
		const tempDir = await fs.promises.mkdtemp(
			path.join(os.tmpdir(), `ddex-${snapshotId.slice(0, 8)}-`),
		);

		try {
			// 5. Create folder structure
			const resourcesDir = path.join(outputDir, 'resources');
			fs.mkdirSync(resourcesDir, { recursive: true });

			// 6. Download media files from bucket → temp → resources/
			await this.downloadMediaFiles(payload, resourcesDir, tempDir);

			// 7. Map snapshot → ErnInput2
			const ernInput = mapSnapshotToErnInput(payload, {
				ernVersion: routingConfig.ernVersion,
				sender: routingConfig.sender,
				recipient: routingConfig.recipient,
			});

			// 8. Generate ERN XML
			const xml = this.ernService.generate(ernInput);
			fs.writeFileSync(path.join(outputDir, 'release.xml'), xml, 'utf-8');

			// 9. Generate manifest if CI aggregator
			if (buildConfig.isAggregator) {
				const manifest = this.ernService.generateManifest({
					sender: {
						partyId: routingConfig.sender.partyId,
						name: routingConfig.sender.name,
					},
					recipient: {
						partyId: routingConfig.recipient.partyId,
						name: routingConfig.recipient.name,
					},
					messages: [
						{
							messageType: 'NewReleaseMessage',
							messageId: payload.upc ?? payload.id,
							url: `${releaseReference}/release.xml`,
							releaseId: { icpn: payload.upc },
						},
					],
				});
				const manifestFileName = `BatchComplete_${batchId}.xml`;
				fs.writeFileSync(
					path.join(this.baseDir, batchId, manifestFileName),
					manifest,
					'utf-8',
				);
				this.logger.log(
					`[build] Manifest written: ${manifestFileName}`,
				);
			}

			this.logger.log(`[build] Package built: ${outputDir}`);
			return PackagePath.create(
				'local',
				`${batchId}/${releaseReference}`,
			);
		} finally {
			// Clean up temp dir
			fs.promises
				.rm(tempDir, { recursive: true, force: true })
				.catch(() => {});
		}
	}

	/**
	 * batchId = tên folder theo convention v3 (YYYYMMDDHHmmssSSS) mà CI aggregator quét.
	 * Sinh mới mỗi lần build (timestamp). Idempotency KHÔNG dựa vào đây mà ở runner guard
	 * (skip nếu dist.packageUri đã set) — xem class doc. `key` giữ trong chữ ký để lớp gọi
	 * truyền idempotency context; nếu sau này cần batchId ổn định theo key (tránh orphan folder
	 * khi build fail giữa chừng rồi retry) thì derive từ key ở đây.
	 */
	private deriveBatchId(_key: IdempotencyKey): string {
		return genBatchId();
	}

	/**
	 * Download audio/cover files from cloud bucket → local resources/ folder.
	 * Uses BucketService2.streamFileToPath (v3 pattern) to fetch files stored during release creation.
	 *
	 * Snapshot payload contains fileId references for coverArt and track audioFiles.
	 */
	private async downloadMediaFiles(
		payload: ReleaseSnapshotPayload,
		resourcesDir: string,
		tempDir: string,
	): Promise<{ coverExtension?: string }> {
		let coverExtension: string | undefined;

		// Download cover art
		const coverArt =
			payload.releaseCoverArts?.find(
				(art) => (art as any).type === 'original',
			) ?? payload.releaseCoverArts?.[0];

		if (coverArt && (coverArt as any).fileId) {
			try {
				const coverTmpPath = path.join(tempDir, 'cover.tmp');
				const fileDb = await this.bucketService.streamFileToPath({
					fileId: (coverArt as any).fileId,
					destPath: coverTmpPath,
				});
				coverExtension = fileDb.extension;

				const ext = this.normalizeImageExtension(
					coverExtension ?? 'jpg',
				);
				const coverFileName = `${payload.upc ?? payload.id}${ext}`;
				fs.copyFileSync(
					coverTmpPath,
					path.join(resourcesDir, coverFileName),
				);
			} catch (err) {
				this.logger.warn(
					`[downloadMediaFiles] Cover download failed: ${(err as Error).message}`,
				);
			}
		}

		// Download audio tracks
		const sortedTracks = [...(payload.tracks ?? [])].sort(
			(a, b) => a.order - b.order,
		);
		for (const [index, track] of sortedTracks.entries()) {
			const audioFileId = (track.audioFile as any)?.fileId;
			if (!audioFileId) continue;

			try {
				const trackTmpPath = path.join(
					tempDir,
					`track_${String(index + 1).padStart(3, '0')}.tmp`,
				);
				const fileDb = await this.bucketService.streamFileToPath({
					fileId: audioFileId,
					destPath: trackTmpPath,
				});
				const ext = fileDb.extension ?? 'wav';
				const audioFileName = `${track.isrc}_T${index}S${this.normalizeAudioExtension(ext)}`;
				fs.copyFileSync(
					trackTmpPath,
					path.join(resourcesDir, audioFileName),
				);
			} catch (err) {
				this.logger.warn(
					`[downloadMediaFiles] Audio download failed for ${track.isrc}: ${(err as Error).message}`,
				);
			}
		}

		return { coverExtension };
	}

	private normalizeImageExtension(ext: string): string {
		const cleaned = ext.replace(/^\./, '').toLowerCase();
		switch (cleaned) {
			case 'jpg':
			case 'jpeg':
				return '.jpg';
			case 'png':
				return '.png';
			default:
				return `.${cleaned}`;
		}
	}

	private normalizeAudioExtension(ext: string): string {
		const cleaned = ext.replace(/^\./, '').toLowerCase();
		switch (cleaned) {
			case 'wav':
				return '.wav';
			case 'flac':
				return '.flac';
			case 'mp3':
				return '.mp3';
			default:
				return `.${cleaned}`;
		}
	}
}
