export enum ReleaseExecutionStatus {
	NEW = 'NEW',
	PROCESSING = 'PROCESSING',
	WAITING_ACTION = 'WAITING_ACTION',
	WAITING_PARTNER = 'WAITING_PARTNER',

	PARTIAL_DONE = 'PARTIAL_DONE',

	SKIPPED = 'SKIPPED',
	DONE = 'DONE',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

export enum ExecutionType {
	INITIAL_RELEASE = 'INITIAL_RELEASE',
	UPDATE = 'UPDATE',
	TAKEDOWN = 'TAKEDOWN',
	RETRY = 'RETRY',
}

export enum ReleaseExecutionStepStatus {
	NEW = 'NEW',
	PROCESSING = 'PROCESSING',
	WAITING_ACTION = 'WAITING_ACTION',
	WAITING_PARTNER = 'WAITING_PARTNER',

	SKIPPED = 'SKIPPED',
	DONE = 'DONE',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

/**
 * Step types — enum chỉ dùng ở code (type safety + autocomplete).
 * DB lưu varchar, nên thêm type mới chỉ cần thêm vào enum này, không cần migration.
 */
export enum ReleaseExecutionStepType {
	// === Root ===
	GEN_UPC = 'GEN_UPC',
	GEN_ISRCS = 'GEN_ISRCS',
	GEN_ISRC = 'GEN_ISRC',
	VALIDATE = 'VALIDATE',
	PROCESS_DSPS = 'PROCESS_DSPS',

	// === Direct DSP ===
	PROCESS_DIRECT = 'PROCESS_DIRECT',
	PROCESS_DIRECT_CHILD = 'PROCESS_DIRECT_CHILD',
	// CREATE_METADATA_ON_SERVER = 'CREATE_METADATA_ON_SERVER',
	// UPLOAD_METADATA_TO_SFTP = 'UPLOAD_METADATA_TO_SFTP
	// WAIT_PARTNER_PROCESS = 'WAIT_PARTNER_PROCESS',
	SYNC_DATA_PARTNER = 'SYNC_DATA_PARTNER',

	// === CI Aggregator ===
	PROCESS_AGG = 'PROCESS_AGG',
	PROCESS_AGG_CI = 'PROCESS_AGG_CI',
	IMPORT_CI = 'IMPORT_CI',
	EXPORT_CI = 'EXPORT_CI',
	// CREATE_METADATA_ON_SERVER = 'CREATE_METADATA_ON_SERVER',
	// UPLOAD_METADATA_TO_SFTP = 'UPLOAD_METADATA_TO_SFTP
	CREATE_FOLDER_DONE_CI = 'CREATE_FOLDER_DONE_CI',
	// WAIT_PARTNER_PROCESS = 'WAIT_PARTNER_PROCESS',
	VALIDATE_QA_CI = 'VALIDATE_QA_CI',

	EXPORT_AGG_CI_CI = 'EXPORT_CI_CI',
	EXPORT_AGG_CI_STATE51 = 'EXPORT_AGG_CI_STATE51',
	WAITING_ADMIN_EXPORT = 'WAITING_ADMIN_EXPORT',
	SEND_EMAIL_STATE51 = 'SEND_EMAIL_STATE51',
	SYNC_DATA_DSP_CI = 'SYNC_DATA_DSP_CI',

	// === Shared ===
	WAIT_PARTNER_PROCESS = 'WAIT_PARTNER_PROCESS',
	CREATE_METADATA_ON_SERVER = 'CREATE_METADATA_ON_SERVER',
	UPLOAD_METADATA_TO_SFTP = 'UPLOAD_METADATA_TO_SFTP',
	SYNC_RESULT_TO_RELEASE = 'SYNC_RESULT_TO_RELEASE',
}

export enum ExecutionStepMode {
	SEQUENTIAL = 'sequential', // chạy tuần tự, bước sau chờ bước trước
	PARALLEL = 'parallel', // chạy đồng thời tất cả
}
