export const GenreMessageCodeSuccess = {
	CREATE: 'genre.message.success.create',
	UPDATE: 'genre.message.success.update',
	DELETE: 'genre.message.success.delete',
};

export const GenreMessageSuccess = {
	CREATE: 'Create success',
	UPDATE: 'Update success',
	DELETE: 'Delete success',
};

const GenreMessageCodeError = {
	DUPLICATE_NAME_GENRE: 'genre.message.error.duplicateNameGenre',
	DUPLICATE_CODE_GENRE: 'genre.message.error.duplicateCodeGenre',
	NOT_FOUND: 'genre.message.error.notFound',
	CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_RELEASES:
		'genre.message.error.cannotDeleteBecauseLinkedPrimaryReleases',
	CANNOT_DELETE_BECAUSE_LINKED_SUB_RELEASES:
		'genre.message.error.cannotDeleteBecauseLinkedSubReleases',
	CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_TRACKS:
		'genre.message.error.cannotDeleteBecauseLinkedPrimaryTracks',
	CANNOT_DELETE_BECAUSE_LINKED_SUB_TRACKS:
		'genre.message.error.cannotDeleteBecauseLinkedSubTracks',
};

const GenreMessageError = {
	DUPLICATE_NAME_GENRE: 'Duplicate genre name',
	DUPLICATE_CODE_GENRE: 'Duplicate genre code',
	NOT_FOUND: 'Not found',
	CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_RELEASES:
		'Cannot delete this genre because it is linked to primary releases.',
	CANNOT_DELETE_BECAUSE_LINKED_SUB_RELEASES:
		'Cannot delete this genre because it is linked to sub-genre releases.',
	CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_TRACKS:
		'Cannot delete this genre because it is linked to primary tracks.',
	CANNOT_DELETE_BECAUSE_LINKED_SUB_TRACKS:
		'Cannot delete this genre because it is linked to sub-genre tracks.',
};

export const GenreMessage = {
	NOT_FOUND: {
		message: GenreMessageError.NOT_FOUND,
		statusCode: 404,
	},

	DUPLICATE_NAME_GENRE: {
		messageCode: GenreMessageCodeError.DUPLICATE_NAME_GENRE,
		message: GenreMessageError.DUPLICATE_NAME_GENRE,
	},

	DUPLICATE_CODE_GENRE: {
		messageCode: GenreMessageCodeError.DUPLICATE_CODE_GENRE,
		message: GenreMessageError.DUPLICATE_CODE_GENRE,
	},

	CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_RELEASES: {
		message:
			GenreMessageError.CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_RELEASES,
		messageCode:
			GenreMessageCodeError.CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_RELEASES,
		statusCode: 400,
	},

	CANNOT_DELETE_BECAUSE_LINKED_SUB_RELEASES: {
		message: GenreMessageError.CANNOT_DELETE_BECAUSE_LINKED_SUB_RELEASES,
		messageCode:
			GenreMessageCodeError.CANNOT_DELETE_BECAUSE_LINKED_SUB_RELEASES,
		statusCode: 400,
	},

	CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_TRACKS: {
		message: GenreMessageError.CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_TRACKS,
		messageCode:
			GenreMessageCodeError.CANNOT_DELETE_BECAUSE_LINKED_PRIMARY_TRACKS,
		statusCode: 400,
	},

	CANNOT_DELETE_BECAUSE_LINKED_SUB_TRACKS: {
		message: GenreMessageError.CANNOT_DELETE_BECAUSE_LINKED_SUB_TRACKS,
		messageCode:
			GenreMessageCodeError.CANNOT_DELETE_BECAUSE_LINKED_SUB_TRACKS,
		statusCode: 400,
	},
};

export const dataInitGenre: { name: string; code: string }[] = [
	{ name: 'African', code: 'AFRICAN' },
	{ name: 'African Dancehall', code: 'AFRICAN_DANCEHALL' },
	{ name: 'African Reggae', code: 'AFRICAN_REGGAE' },
	{ name: 'Afro House', code: 'AFRO_HOUSE' },
	{ name: 'Afro Soul', code: 'AFRO_SOUL' },
	{ name: 'Afro-folk', code: 'AFRO_FOLK' },
	{ name: 'Afro-fusion', code: 'AFRO_FUSION' },
	{ name: 'Afrobeats', code: 'AFROBEATS' },
	{ name: 'Alte', code: 'ALTE' },
	{ name: 'Amapiano', code: 'AMAPIANO' },
	{ name: 'Benga', code: 'BENGA' },
	{ name: 'Bongo-Flava', code: 'BONGO_FLAVA' },
	{ name: 'Coupé-Décalé', code: 'COUPE_DECALE' },
	{ name: 'Gqom', code: 'GQOM' },
	{ name: 'Highlife', code: 'HIGHLIFE' },
	{ name: 'Kizomba', code: 'KIZOMBA' },
	{ name: 'Kuduro', code: 'KUDURO' },
	{ name: 'Kwaito', code: 'KWAITO' },
	{ name: 'Maskandi', code: 'MASKANDI' },
	{ name: 'Mbalax', code: 'MBALAX' },
	{ name: 'Ndombolo', code: 'NDOMBOLO' },
	{ name: 'Shangaan Electro', code: 'SHANGAAN_ELECTRO' },
	{ name: 'Soukous', code: 'SOUKOUS' },
	{ name: 'Taarab', code: 'TAARAB' },
	{ name: 'Zouglou', code: 'ZOUGLOU' },
	{ name: 'Alternative', code: 'ALTERNATIVE' },
	{ name: 'College Rock', code: 'COLLEGE_ROCK' },
	{ name: 'EMO', code: 'EMO' },
	{ name: 'Goth Rock', code: 'GOTH_ROCK' },
	{ name: 'Grunge', code: 'GRUNGE' },
	{ name: 'Indie Egyptian', code: 'INDIE_EGYPTIAN' },
	{ name: 'Indie Levant', code: 'INDIE_LEVANT' },
	{ name: 'Indie Maghreb', code: 'INDIE_MAGHREB' },
	{ name: 'Indie Pop', code: 'INDIE_POP' },
	{ name: 'Indie Rock', code: 'INDIE_ROCK' },
	{ name: 'New Wave', code: 'NEW_WAVE' },
	{ name: 'Pop Punk', code: 'POP_PUNK' },
	{ name: 'Punk', code: 'PUNK' },
	{ name: 'Anime', code: 'ANIME' },
	{ name: 'Arabic', code: 'ARABIC' },
	{ name: 'Arabic Pop', code: 'ARABIC_POP' },
	{ name: 'Dabke', code: 'DABKE' },
	{ name: 'Islamic', code: 'ISLAMIC' },
	{ name: 'Khaleeji', code: 'KHALEEJI' },
	{ name: 'Khaleeji Jalsat', code: 'KHALEEJI_JALSAT' },
	{ name: 'Khaleeji Shailat', code: 'KHALEEJI_SHAILAT' },
	{ name: 'Levant', code: 'LEVANT' },
	{ name: 'Maghreb Rai', code: 'MAGHREB_RAI' },
	{ name: 'North African', code: 'NORTH_AFRICAN' },
	{ name: 'Blues', code: 'BLUES' },
	{ name: 'Acoustic Blues', code: 'ACOUSTIC_BLUES' },
	{ name: 'Chicago Blues', code: 'CHICAGO_BLUES' },
	{ name: 'Classic Blues', code: 'CLASSIC_BLUES' },
	{ name: 'Contemporary Blues', code: 'CONTEMPORARY_BLUES' },
	{ name: 'Country Blues', code: 'COUNTRY_BLUES' },
	{ name: 'Delta Blues', code: 'DELTA_BLUES' },
	{ name: 'Electric Blues', code: 'ELECTRIC_BLUES' },
	{ name: 'Brazilian', code: 'BRAZILIAN' },
	{ name: 'Axé', code: 'AXE' },
	{ name: 'Baile Funk', code: 'BAILE_FUNK' },
	{ name: 'Bossa Nova', code: 'BOSSA_NOVA' },
	{ name: 'Choro', code: 'CHORO' },
	{ name: 'Forró', code: 'FORRO' },
	{ name: 'Frevo', code: 'FREVO' },
	{ name: 'MPB', code: 'MPB' },
	{ name: 'Pagode', code: 'PAGODE' },
	{ name: 'Samba', code: 'SAMBA' },
	{ name: 'Sertanejo', code: 'SERTANEJO' },
	{ name: "Children's Music", code: 'CHILDRENS_MUSIC' },
	{ name: 'Lullabies', code: 'LULLABIES' },
	{ name: 'Sing-Along', code: 'SING_ALONG' },
	{ name: 'Stories', code: 'STORIES' },
	{ name: 'Chinese', code: 'CHINESE' },
	{ name: 'Cantopop', code: 'CANTOPOP' },
	{ name: 'Chinese Alt', code: 'CHINESE_ALT' },
	{ name: 'Chinese Classical', code: 'CHINESE_CLASSICAL' },
	{ name: 'Chinese Flute', code: 'CHINESE_FLUTE' },
	{ name: 'Chinese Hip-Hop', code: 'CHINESE_HIP_HOP' },
	{ name: 'Chinese Opera', code: 'CHINESE_OPERA' },
	{ name: 'Chinese Orchestral', code: 'CHINESE_ORCHESTRAL' },
	{ name: 'Chinese Regional Folk', code: 'CHINESE_REGIONAL_FOLK' },
	{ name: 'Chinese Rock', code: 'CHINESE_ROCK' },
	{ name: 'Chinese Strings', code: 'CHINESE_STRINGS' },
	{ name: 'Taiwanese Folk', code: 'TAIWANESE_FOLK' },
	{ name: 'Tibetan Native Music', code: 'TIBETAN_NATIVE_MUSIC' },
	{ name: 'Christian & Gospel', code: 'CHRISTIAN_AND_GOSPEL' },
	{ name: 'CCM', code: 'CCM' },
	{ name: 'Christian Metal', code: 'CHRISTIAN_METAL' },
	{ name: 'Christian Pop', code: 'CHRISTIAN_POP' },
	{ name: 'Christian Rap', code: 'CHRISTIAN_RAP' },
	{ name: 'Christian Rock', code: 'CHRISTIAN_ROCK' },
	{ name: 'Classic Christian', code: 'CLASSIC_CHRISTIAN' },
	{ name: 'Contemporary Gospel', code: 'CONTEMPORARY_GOSPEL' },
	{ name: 'Gospel', code: 'GOSPEL' },
	{ name: 'Praise & Worship', code: 'PRAISE_AND_WORSHIP' },
	{ name: 'Southern Gospel', code: 'SOUTHERN_GOSPEL' },
	{ name: 'Traditional Gospel', code: 'TRADITIONAL_GOSPEL' },
	{ name: 'Classical', code: 'CLASSICAL' },
	{ name: '(Classical) Electronic', code: 'CLASSICAL_ELECTRONIC' },
	{ name: '(Classical) Orchestral', code: 'CLASSICAL_ORCHESTRAL' },
	{ name: 'Art Song', code: 'ART_SONG' },
	{ name: 'Avant-Garde', code: 'AVANT_GARDE' },
	{ name: 'Baroque Era', code: 'BAROQUE_ERA' },
	{ name: 'Brass & Woodwinds', code: 'BRASS_AND_WOODWINDS' },
	{ name: 'Cantata', code: 'CANTATA' },
	{ name: 'Cello', code: 'CELLO' },
	{ name: 'Chamber Music', code: 'CHAMBER_MUSIC' },
	{ name: 'Chant', code: 'CHANT' },
	{ name: 'Choral', code: 'CHORAL' },
	{ name: 'Classical Crossover', code: 'CLASSICAL_CROSSOVER' },
	{ name: 'Classical Era', code: 'CLASSICAL_ERA' },
	{ name: 'Contemporary Era', code: 'CONTEMPORARY_ERA' },
	{ name: 'Early Music', code: 'EARLY_MUSIC' },
	{ name: 'Guitar', code: 'GUITAR' },
	{ name: 'Impressionist', code: 'IMPRESSIONIST' },
	{ name: 'Medieval Era', code: 'MEDIEVAL_ERA' },
	{ name: 'Minimalism', code: 'MINIMALISM' },
	{ name: 'Modern Era', code: 'MODERN_ERA' },
	{ name: 'Oratorio', code: 'ORATORIO' },
	{ name: 'Percussion', code: 'PERCUSSION' },
	{ name: 'Piano', code: 'PIANO' },
	{ name: 'Renaissance', code: 'RENAISSANCE' },
	{ name: 'Romantic Era', code: 'ROMANTIC_ERA' },
	{ name: 'Sacred', code: 'SACRED' },
	{ name: 'Solo Instrumental', code: 'SOLO_INSTRUMENTAL' },
	{ name: 'Violin', code: 'VIOLIN' },
	{ name: 'Wedding Music', code: 'WEDDING_MUSIC' },
	{ name: 'Comedy', code: 'COMEDY' },
	{ name: 'Novelty', code: 'NOVELTY' },
	{ name: 'Standup Comedy', code: 'STANDUP_COMEDY' },
	{ name: 'Country', code: 'COUNTRY' },
	{ name: 'Alternative Country', code: 'ALTERNATIVE_COUNTRY' },
	{ name: 'Americana', code: 'AMERICANA' },
	{ name: 'Bluegrass', code: 'BLUEGRASS' },
	{ name: 'Contemporary Bluegrass', code: 'CONTEMPORARY_BLUEGRASS' },
	{ name: 'Contemporary Country', code: 'CONTEMPORARY_COUNTRY' },
	{ name: 'Country Gospel', code: 'COUNTRY_GOSPEL' },
	{ name: 'Honky Tonk', code: 'HONKY_TONK' },
	{ name: 'Outlaw Country', code: 'OUTLAW_COUNTRY' },
	{ name: 'Thai Country', code: 'THAI_COUNTRY' },
	{ name: 'Traditional Bluegrass', code: 'TRADITIONAL_BLUEGRASS' },
	{ name: 'Traditional Country', code: 'TRADITIONAL_COUNTRY' },
	{ name: 'Urban Cowboy', code: 'URBAN_COWBOY' },
	{ name: 'Cuban', code: 'CUBAN' },
	{ name: 'Bolero', code: 'BOLERO' },
	{ name: 'Chachacha', code: 'CHACHACHA' },
	{ name: 'Guajira', code: 'GUAJIRA' },
	{ name: 'Guaracha', code: 'GUARACHA' },
	{ name: 'Mambo', code: 'MAMBO' },
	{ name: 'Son', code: 'SON' },
	{ name: 'Timba', code: 'TIMBA' },
	{ name: 'Dance', code: 'DANCE' },
	{ name: 'Breakbeat', code: 'BREAKBEAT' },
	{ name: 'Garage', code: 'GARAGE' },
	{ name: 'Hardcore', code: 'HARDCORE' },
	{ name: 'House', code: 'HOUSE' },
	{ name: "Jungle/Drum'n'bass", code: 'JUNGLE_DRUM_N_BASS' },
	{ name: 'Maghreb Dance', code: 'MAGHREB_DANCE' },
	{ name: 'Psy-Trance', code: 'PSY_TRANCE' },
	{ name: 'Techno', code: 'TECHNO' },
	{ name: 'Trance', code: 'TRANCE' },
	{ name: 'Disney', code: 'DISNEY' },
	{ name: 'Easy Listening', code: 'EASY_LISTENING' },
	{ name: 'Lounge', code: 'LOUNGE' },
	{ name: 'Swing', code: 'SWING' },
	{ name: 'Electronic', code: 'ELECTRONIC' },
	{ name: 'Ambient', code: 'AMBIENT' },
	{ name: 'Bass', code: 'BASS' },
	{ name: 'Downtempo', code: 'DOWNTEMPO' },
	{ name: 'Dubstep', code: 'DUBSTEP' },
	{ name: "Electro-Cha'abi", code: 'ELECTRO_CHA_ABI' },
	{ name: 'Electronica', code: 'ELECTRONICA' },
	{ name: 'IDM/Experimental', code: 'IDM_EXPERIMENTAL' },
	{ name: 'Industrial', code: 'INDUSTRIAL' },
	{ name: 'Levant Electronic', code: 'LEVANT_ELECTRONIC' },
	{ name: 'Maghreb Electronic', code: 'MAGHREB_ELECTRONIC' },
	{ name: 'Fitness & Workout', code: 'FITNESS_AND_WORKOUT' },
	{ name: 'Folk', code: 'FOLK' },
	{ name: 'Iraqi Folk', code: 'IRAQI_FOLK' },
	{ name: 'Khaleeji Folk', code: 'KHALEEJI_FOLK' },
	{ name: 'Hip Hop/Rap', code: 'HIP_HOP_RAP' },
	{ name: 'Alternative Rap', code: 'ALTERNATIVE_RAP' },
	{ name: 'Dirty South', code: 'DIRTY_SOUTH' },
	{ name: 'East Coast Rap', code: 'EAST_COAST_RAP' },
	{ name: 'Egyptian Hip-Hop', code: 'EGYPTIAN_HIP_HOP' },
	{ name: 'Gangsta Rap', code: 'GANGSTA_RAP' },
	{ name: 'Hardcore Rap', code: 'HARDCORE_RAP' },
	{ name: 'Hip-Hop', code: 'HIP_HOP' },
	{ name: 'Khaleeji Hip-Hop', code: 'KHALEEJI_HIP_HOP' },
	{ name: 'Latin Rap', code: 'LATIN_RAP' },
	{ name: 'Levant Hip-Hop', code: 'LEVANT_HIP_HOP' },
	{ name: 'Maghreb Hip-Hop', code: 'MAGHREB_HIP_HOP' },
	{ name: 'Old School Rap', code: 'OLD_SCHOOL_RAP' },
	{ name: 'Rap', code: 'RAP' },
	{ name: 'Russian Hip-Hop', code: 'RUSSIAN_HIP_HOP' },
	{ name: 'Turkish Hip-Hop/Rap', code: 'TURKISH_HIP_HOP_RAP' },
	{ name: 'UK Hip Hop', code: 'UK_HIP_HOP' },
	{ name: 'Underground Rap', code: 'UNDERGROUND_RAP' },
	{ name: 'West Coast Rap', code: 'WEST_COAST_RAP' },
	{ name: 'Holiday', code: 'HOLIDAY' },
	{ name: 'Chanukah', code: 'CHANUKAH' },
	{ name: 'Christmas', code: 'CHRISTMAS' },
	{ name: "Christmas: Children's", code: 'CHRISTMAS_CHILDRENS' },
	{ name: 'Christmas: Classic', code: 'CHRISTMAS_CLASSIC' },
	{ name: 'Christmas: Classical', code: 'CHRISTMAS_CLASSICAL' },
	{ name: 'Christmas: Country', code: 'CHRISTMAS_COUNTRY' },
	{ name: 'Christmas: Jazz', code: 'CHRISTMAS_JAZZ' },
	{ name: 'Christmas: Modern', code: 'CHRISTMAS_MODERN' },
	{ name: 'Christmas: Pop', code: 'CHRISTMAS_POP' },
	{ name: 'Christmas: R&B', code: 'CHRISTMAS_R_AND_B' },
	{ name: 'Christmas: Religious', code: 'CHRISTMAS_RELIGIOUS' },
	{ name: 'Christmas: Rock', code: 'CHRISTMAS_ROCK' },
	{ name: 'Easter', code: 'EASTER' },
	{ name: 'Halloween', code: 'HALLOWEEN' },
	{ name: 'Thanksgiving', code: 'THANKSGIVING' },
	{ name: 'Hörspiele', code: 'HORSPIELE' },
	{ name: 'Indian', code: 'INDIAN' },
	{ name: 'Bollywood', code: 'BOLLYWOOD' },
	{ name: 'Devotional & Spiritual', code: 'DEVOTIONAL_AND_SPIRITUAL' },
	{ name: 'Ghazals', code: 'GHAZALS' },
	{ name: 'Indian Folk', code: 'INDIAN_FOLK' },
	{ name: 'Indian Pop', code: 'INDIAN_POP' },
	{ name: 'Sufi', code: 'SUFI' },
	{ name: 'Tamil', code: 'TAMIL' },
	{ name: 'Telugu', code: 'TELUGU' },
	{ name: 'Indian Classical', code: 'INDIAN_CLASSICAL' },
	{ name: 'Carnatic Classical', code: 'CARNATIC_CLASSICAL' },
	{ name: 'Hindustani Classical', code: 'HINDUSTANI_CLASSICAL' },
	{ name: 'Inspirational', code: 'INSPIRATIONAL' },
	{ name: 'Instrumental', code: 'INSTRUMENTAL' },
	{ name: 'Jazz', code: 'JAZZ' },
	{ name: '(Jazz) Latin Jazz', code: 'JAZZ_LATIN_JAZZ' },
	{ name: 'Avant-Garde Jazz', code: 'AVANT_GARDE_JAZZ' },
	{ name: 'Bebop', code: 'BEBOP' },
	{ name: 'Big Band', code: 'BIG_BAND' },
	{ name: 'Contemporary Jazz', code: 'CONTEMPORARY_JAZZ' },
	{ name: 'Cool', code: 'COOL' },
	{ name: 'Crossover Jazz', code: 'CROSSOVER_JAZZ' },
	{ name: 'Dixieland', code: 'DIXIELAND' },
	{ name: 'Fusion', code: 'FUSION' },
	{ name: 'Hard Bop', code: 'HARD_BOP' },
	{ name: 'Mainstream Jazz', code: 'MAINSTREAM_JAZZ' },
	{ name: 'Ragtime', code: 'RAGTIME' },
	{ name: 'Smooth Jazz', code: 'SMOOTH_JAZZ' },
	{ name: 'Trad Jazz', code: 'TRAD_JAZZ' },
	{ name: 'Karaoke', code: 'KARAOKE' },
	{ name: 'Korean', code: 'KOREAN' },
	{ name: 'K-Pop', code: 'K_POP' },
	{ name: 'Korean Folk-Pop', code: 'KOREAN_FOLK_POP' },
	{ name: 'Korean Hip-Hop', code: 'KOREAN_HIP_HOP' },
	{ name: 'Korean Indie', code: 'KOREAN_INDIE' },
	{ name: 'Korean Rock', code: 'KOREAN_ROCK' },
	{ name: 'Korean Traditional', code: 'KOREAN_TRADITIONAL' },
	{ name: 'Latin', code: 'LATIN' },
	{
		name: 'Alternative & Rock in Spanish',
		code: 'ALTERNATIVE_AND_ROCK_IN_SPANISH',
	},
	{ name: 'Bachata', code: 'BACHATA' },
	{ name: 'Baladas y Boleros', code: 'BALADAS_Y_BOLEROS' },
	{ name: 'Contemporary Latin', code: 'CONTEMPORARY_LATIN' },
	{ name: 'Cumbia', code: 'CUMBIA' },
	{ name: 'Latin Jazz', code: 'LATIN_JAZZ' },
	{ name: 'Merengue', code: 'MERENGUE' },
	{ name: 'Pop in Spanish', code: 'POP_IN_SPANISH' },
	{ name: 'Raices', code: 'RAICES' },
	{ name: 'Reggaeton / Latin Urban', code: 'REGGAETON_LATIN_URBAN' },
	{ name: 'Regional Mexicano', code: 'REGIONAL_MEXICANO' },
	{ name: 'Salsa y Tropical', code: 'SALSA_Y_TROPICAL' },
	{ name: 'Marching Bands', code: 'MARCHING_BANDS' },
	{ name: 'New Age', code: 'NEW_AGE' },
	{ name: 'Healing', code: 'HEALING' },
	{ name: 'Meditation', code: 'MEDITATION' },
	{ name: 'Nature', code: 'NATURE' },
	{ name: 'Relaxation', code: 'RELAXATION' },
	{ name: 'Travel', code: 'TRAVEL' },
	{ name: 'Yoga', code: 'YOGA' },
	{ name: 'Opera', code: 'OPERA' },
	{ name: 'Orchestral', code: 'ORCHESTRAL' },
	{ name: 'Pop', code: 'POP' },
	{ name: 'Adult Contemporary', code: 'ADULT_CONTEMPORARY' },
	{ name: 'Britpop', code: 'BRITPOP' },
	{ name: 'Egyptian Pop', code: 'EGYPTIAN_POP' },
	{ name: 'French Pop', code: 'FRENCH_POP' },
	{ name: 'German Pop', code: 'GERMAN_POP' },
	{ name: 'Indo Pop', code: 'INDO_POP' },
	{ name: 'Iraqi Pop', code: 'IRAQI_POP' },
	{ name: 'J-Pop', code: 'J_POP' },
	{ name: 'Kayokyoku', code: 'KAYOKYOKU' },
	{ name: 'Khaleeji Pop', code: 'KHALEEJI_POP' },
	{ name: 'Levant Pop', code: 'LEVANT_POP' },
	{ name: 'Maghreb Pop', code: 'MAGHREB_POP' },
	{ name: 'Malaysian Pop', code: 'MALAYSIAN_POP' },
	{ name: 'Mandopop', code: 'MANDOPOP' },
	{ name: 'Manilla Sound', code: 'MANILLA_SOUND' },
	{ name: 'Oldies', code: 'OLDIES' },
	{ name: 'Original Pilipino Music', code: 'ORIGINAL_PILIPINO_MUSIC' },
	{ name: 'Pinoy Pop', code: 'PINOY_POP' },
	{ name: 'Pop/Rock', code: 'POP_ROCK' },
	{ name: 'Russian Pop', code: 'RUSSIAN_POP' },
	{ name: 'Shows', code: 'SHOWS' },
	{ name: 'Soft Rock', code: 'SOFT_ROCK' },
	{ name: 'Tai-Pop', code: 'TAI_POP' },
	{ name: 'Teen Pop', code: 'TEEN_POP' },
	{ name: 'Thai Pop', code: 'THAI_POP' },
	{ name: 'R&B/Soul', code: 'R_AND_B_SOUL' },
	{ name: 'Contemporary R&B', code: 'CONTEMPORARY_R_AND_B' },
	{ name: 'Disco', code: 'DISCO' },
	{ name: 'Doo Wop', code: 'DOO_WOP' },
	{ name: 'Funk', code: 'FUNK' },
	{ name: 'Motown', code: 'MOTOWN' },
	{ name: 'Neo-Soul', code: 'NEO_SOUL' },
	{ name: 'Soul', code: 'SOUL' },
	{ name: 'Reggae', code: 'REGGAE' },
	{ name: 'Classic/Modern Dancehall', code: 'CLASSIC_MODERN_DANCEHALL' },
	{ name: 'Dub', code: 'DUB' },
	{ name: 'Lovers Rock', code: 'LOVERS_ROCK' },
	{ name: 'Roots Reggae', code: 'ROOTS_REGGAE' },
	{ name: 'Ska', code: 'SKA' },
	{ name: 'Regional Indian', code: 'REGIONAL_INDIAN' },
	{ name: 'Assamese', code: 'ASSAMESE' },
	{ name: 'Bengali', code: 'BENGALI' },
	{ name: 'Bhojpuri', code: 'BHOJPURI' },
	{ name: 'Gujarati', code: 'GUJARATI' },
	{ name: 'Haryanvi', code: 'HARYANVI' },
	{ name: 'Kannada', code: 'KANNADA' },
	{ name: 'Malayalam', code: 'MALAYALAM' },
	{ name: 'Marathi', code: 'MARATHI' },
	{ name: 'Odia', code: 'ODIA' },
	{ name: 'Punjabi', code: 'PUNJABI' },
	{ name: 'Punjabi Pop', code: 'PUNJABI_POP' },
	{ name: 'Rabindra Sangeet', code: 'RABINDRA_SANGEET' },
	{ name: 'Rajasthani', code: 'RAJASTHANI' },
	{ name: 'Urdu', code: 'URDU' },
	{ name: 'Rock', code: 'ROCK' },
	{ name: '(Rock) Singer/Songwriter', code: 'ROCK_SINGER_SONGWRITER' },
	{ name: 'Adult Alternative', code: 'ADULT_ALTERNATIVE' },
	{ name: 'American Trad Rock', code: 'AMERICAN_TRAD_ROCK' },
	{ name: 'Arena Rock', code: 'ARENA_ROCK' },
	{ name: 'Blues-Rock', code: 'BLUES_ROCK' },
	{ name: 'British Invasion', code: 'BRITISH_INVASION' },
	{ name: 'Death Metal/Black Metal', code: 'DEATH_METAL_BLACK_METAL' },
	{ name: 'Glam Rock', code: 'GLAM_ROCK' },
	{ name: 'Hair Metal', code: 'HAIR_METAL' },
	{ name: 'Hard Rock', code: 'HARD_ROCK' },
	{ name: 'Heavy Metal', code: 'HEAVY_METAL' },
	{ name: 'Jam Bands', code: 'JAM_BANDS' },
	{ name: 'Prog-Rock/Art Rock', code: 'PROG_ROCK_ART_ROCK' },
	{ name: 'Psychedelic', code: 'PSYCHEDELIC' },
	{ name: 'Rock & Roll', code: 'ROCK_AND_ROLL' },
	{ name: 'Rockabilly', code: 'ROCKABILLY' },
	{ name: 'Roots Rock', code: 'ROOTS_ROCK' },
	{ name: 'Russian Rock', code: 'RUSSIAN_ROCK' },
	{ name: 'Southern Rock', code: 'SOUTHERN_ROCK' },
	{ name: 'Surf', code: 'SURF' },
	{ name: 'Tex-Mex', code: 'TEX_MEX' },
	{ name: 'Russian', code: 'RUSSIAN' },
	{ name: 'Russian Bard', code: 'RUSSIAN_BARD' },
	{ name: 'Russian Romance', code: 'RUSSIAN_ROMANCE' },
	{ name: 'Singer/Songwriter', code: 'SINGER_SONGWRITER' },
	{ name: 'Alternative Folk', code: 'ALTERNATIVE_FOLK' },
	{ name: 'Contemporary Folk', code: 'CONTEMPORARY_FOLK' },
	{
		name: 'Contemporary Singer/Songwriter',
		code: 'CONTEMPORARY_SINGER_SONGWRITER',
	},
	{ name: 'Folk-Rock', code: 'FOLK_ROCK' },
	{ name: 'New Acoustic', code: 'NEW_ACOUSTIC' },
	{ name: 'Traditional Folk', code: 'TRADITIONAL_FOLK' },
	{ name: 'Soundtrack', code: 'SOUNDTRACK' },
	{ name: 'Film Soundtrack', code: 'FILM_SOUNDTRACK' },
	{ name: 'Foreign Cinema', code: 'FOREIGN_CINEMA' },
	{ name: 'Musicals', code: 'MUSICALS' },
	{ name: 'Original Score', code: 'ORIGINAL_SCORE' },
	{ name: 'Sound Effects', code: 'SOUND_EFFECTS' },
	{ name: 'TV Soundtrack', code: 'TV_SOUNDTRACK' },
	{ name: 'Video Game', code: 'VIDEO_GAME' },
	{ name: 'Spoken Word', code: 'SPOKEN_WORD' },
	{ name: 'Tarab', code: 'TARAB' },
	{ name: 'Egyptian Tarab', code: 'EGYPTIAN_TARAB' },
	{ name: 'Iraqi Tarab', code: 'IRAQI_TARAB' },
	{ name: 'Khaleeji Tarab', code: 'KHALEEJI_TARAB' },
	{ name: 'Turkish', code: 'TURKISH' },
	{ name: 'Fantezi', code: 'FANTEZI' },
	{ name: 'Religious', code: 'RELIGIOUS' },
	{ name: 'Turkish Alternative', code: 'TURKISH_ALTERNATIVE' },
	{ name: 'Turkish Pop', code: 'TURKISH_POP' },
	{ name: 'Turkish Rock', code: 'TURKISH_ROCK' },
	{ name: 'Özgün', code: 'OZGUN' },
	{ name: 'Vocal', code: 'VOCAL' },
	{ name: 'Standards', code: 'STANDARDS' },
	{ name: 'Traditional Pop', code: 'TRADITIONAL_POP' },
	{ name: 'Trot', code: 'TROT' },
	{ name: 'Vocal Jazz', code: 'VOCAL_JAZZ' },
	{ name: 'Vocal Pop', code: 'VOCAL_POP' },
	{ name: 'World', code: 'WORLD' },
	{ name: 'Afrikaans', code: 'AFRIKAANS' },
	{ name: 'Afro-Beat', code: 'AFRO_BEAT' },
	{ name: 'Afro-Pop', code: 'AFRO_POP' },
	{ name: 'Arabesque', code: 'ARABESQUE' },
	{ name: 'Asia', code: 'ASIA' },
	{ name: 'Australia', code: 'AUSTRALIA' },
	{ name: 'Cajun', code: 'CAJUN' },
	{ name: 'Calypso', code: 'CALYPSO' },
	{ name: 'Caribbean', code: 'CARIBBEAN' },
	{ name: 'Celtic', code: 'CELTIC' },
	{ name: 'Celtic Folk', code: 'CELTIC_FOLK' },
	{ name: 'Contemporary Celtic', code: 'CONTEMPORARY_CELTIC' },
	{ name: 'Dangdut', code: 'DANGDUT' },
	{ name: 'Dini', code: 'DINI' },
	{ name: 'Enka', code: 'ENKA' },
	{ name: 'Europe', code: 'EUROPE' },
	{ name: 'Fado', code: 'FADO' },
	{ name: 'Farsi', code: 'FARSI' },
	{ name: 'Flamenco', code: 'FLAMENCO' },
	{ name: 'France', code: 'FRANCE' },
	{ name: 'German Folk', code: 'GERMAN_FOLK' },
	{ name: 'Halk', code: 'HALK' },
	{ name: 'Hawaii', code: 'HAWAII' },
	{ name: 'Iberia', code: 'IBERIA' },
	{ name: 'Indonesian Religious', code: 'INDONESIAN_RELIGIOUS' },
	{ name: 'Israeli', code: 'ISRAELI' },
	{ name: 'Japan', code: 'JAPAN' },
	{ name: 'Klezmer', code: 'KLEZMER' },
	{ name: 'North America', code: 'NORTH_AMERICA' },
	{ name: 'Polka', code: 'POLKA' },
	{ name: 'Russian Chanson', code: 'RUSSIAN_CHANSON' },
	{ name: 'Sanat', code: 'SANAT' },
	{ name: 'Soca', code: 'SOCA' },
	{ name: 'South Africa', code: 'SOUTH_AFRICA' },
	{ name: 'South America', code: 'SOUTH_AMERICA' },
	{ name: 'Tango', code: 'TANGO' },
	{ name: 'Traditional Celtic', code: 'TRADITIONAL_CELTIC' },
	{ name: 'Worldbeat', code: 'WORLDBEAT' },
	{ name: 'Zydeco', code: 'ZYDECO' },
];
