import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1773902151933 implements MigrationInterface {
    name = 'Migration1773902151933'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "files" DROP COLUMN "storage_provider"`);
        await queryRunner.query(`DROP TYPE "public"."files_storage_provider_enum"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP COLUMN "min_track_count"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP COLUMN "max_track_count"`);
        await queryRunner.query(`ALTER TABLE "releases" ADD "release_original_date" date`);
        await queryRunner.query(`COMMENT ON COLUMN "releases"."release_original_date" IS 'Ngày phát hành gốc Nullable when status is draft'`);
        await queryRunner.query(`ALTER TABLE "audio_files" DROP CONSTRAINT "FK_4d256e74fdf7dfc7fe3db8646d4"`);
        await queryRunner.query(`ALTER TABLE "audio_files" DROP CONSTRAINT "FK_65545b07c020cbdbbb7681608c2"`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" DROP CONSTRAINT "FK_67b825654a61e772db54cd3ae30"`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "audio_files" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "audio_files" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_artist" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_artist" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_language" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_language" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_localize" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_localize" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_scan_histories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_scan_histories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "price_tiers" DROP CONSTRAINT "FK_17a45017ebe3e6d8927e89067b8"`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_0693a1a86145ed3e897ebe2f407"`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_contributors" DROP CONSTRAINT "FK_2dfa99602df7a4afba91716dd8b"`);
        await queryRunner.query(`ALTER TABLE "track_contributors" DROP CONSTRAINT "FK_97b106f98cb47ae955d8866cb7f"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_contributors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_contributors" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_bfba46e5d7c2ebed72f137ece6f"`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dsp_action" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsp_action" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dsp_action" DROP CONSTRAINT "FK_3605a7ccb2c31283c2f438d42d6"`);
        await queryRunner.query(`ALTER TABLE "track_policy" DROP CONSTRAINT "FK_d75145347d0d7237e7b3ada91e9"`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_policy" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_policy" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_45af201b468843adc0043376602"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_22d6e3e276290bd8aba903d0e28"`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_artist" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_artist" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_territories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_territories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_ff54e283e446c9cc70110512028"`);
        await queryRunner.query(`ALTER TABLE "timezones" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "timezones" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_localize" DROP CONSTRAINT "FK_a21be0af831df856191968f2aec"`);
        await queryRunner.query(`ALTER TABLE "release_artist" DROP CONSTRAINT "FK_1d817cf036975de7f3bbfecae31"`);
        await queryRunner.query(`ALTER TABLE "release_contributors" DROP CONSTRAINT "FK_f70e699e006d0dfa5b4c92562b1"`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" DROP CONSTRAINT "FK_3a6a2583bb9d384c77d45aab213"`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" DROP CONSTRAINT "FK_d5113bb1940e63d7cdeb9bae61b"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_90744b146ead957272664ad340a"`);
        await queryRunner.query(`ALTER TABLE "release_territories" DROP CONSTRAINT "FK_513f1ce32ea2c51d0630869efbd"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_233b4896b79bc3a09fe2e7cd33e"`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" DROP CONSTRAINT "FK_c921bcd2b55a7bd206a8b4845df"`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_localize" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_localize" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_localize" DROP CONSTRAINT "FK_ee18fb83969889a91ce89fa1ae1"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_f1c716d09fb61384da50e0b33fe"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_200409e6c7f867e159e2fb55bac"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_7ca6e761a24b38013ad38713aa5"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_925cc591b88a93fc66156432dec"`);
        await queryRunner.query(`ALTER TABLE "track_localize" DROP CONSTRAINT "FK_2a1ac178b973083122b1d4d2f39"`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_language" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_language" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_84fc2bd2d4fc89e5a8585be1818"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_460ef864795eb1672e48089c354"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_80c457bc2a7f83aa7a38f07abcc"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_5139ae6a60c799552ba18c91c68"`);
        await queryRunner.query(`ALTER TABLE "countries" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "countries" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_18828d31d8180ad73610dd9de9a"`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_3ccfc197769ff601f52ea2d81a7"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_43d8e67e7e017c92f243e92f21e"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_9534d65dd5c6bf747bf5ce7d0aa"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_98f690758f195a09664c15bae27"`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" DROP CONSTRAINT "FK_fc14ecc0354329d0dabef1d337d"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_3ba5b99092625b7108b691b9bd1"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_3fcaa9dbb974f9b1fdccc196926"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_bb2a90ed37750405dd793f3d7ff"`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" DROP CONSTRAINT "FK_62d261b9ed07a51e7fa59c472a9"`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" DROP CONSTRAINT "FK_56255bf923a734bf9d9dff70430"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_45a949df1819b8e0040aace0ed1"`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_fa651daf7ef8e110e11a36df797"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_685eabfd94dcce03a30345f458e"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_5bf30c50d712bae277ca356acea"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_c14b165d66f89b256290ca482c6"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_7788db4a1a36cc35260f185b20c"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_047b7db2840104d32fdf49c14d9"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_861431344e4be139790d9e4aac4"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_6a47d535420458cb4e3e9cace59"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_b4634db530af2d532e8c028f94e"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_08a38106bfe4de059e116ef5158"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_1a821992044479ed14974c1aaca"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_f569348fea9ac58ad1013e763a3"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_7528099678299bda1214e4581d7"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_0fae20a96808b8847db8d46935b"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0df30683d0f67875fb6a610a01e"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_5508f9fce2612d730d956fb8f19"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_007676689ebd5d5eca653c05d13"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_df81a19c7525b652c7badd3764c"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_1ed4230ec7b7ca4041402df9b59"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_f06a5757cf435fd81c0730e5778"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_d7e987969e72adacb877570995d"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_1b229bcb849cee7d07a3d127683"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_efba90c155ec02ae586fb7ed31d"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_c3858ff058f009666f469464fc9"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_e55f9cec9169401256cd9f07b60"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_6882fa38fefa198de81b286342f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_eebaffddb3c6e049fa709e7de02"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4fa3646aeebcfb0cd9419dcec9d"`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "role_permission" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role_permission" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery_logs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_e09fc99c2c4f0a1e6f5bbdfd0a8"`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_2848b2477636440af4de2858045"`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "file_node" DROP CONSTRAINT "FK_b166ac92d5e06acd0e769242e1a"`);
        await queryRunner.query(`ALTER TABLE "file_node" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_node" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "backups" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "backups" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "batch_import_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "batch_import_logs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "app_config" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_config" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" DROP CONSTRAINT "FK_04ccdbab2a9b025e4eab834b2c9"`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" DROP CONSTRAINT "FK_ba1bbac7f0863173f40863e272c"`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" DROP CONSTRAINT "FK_3f1bd64741fa999af4bda1e5498"`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" ALTER COLUMN "id" SET DEFAULT gen_random_uuid()`);
        await queryRunner.query(`ALTER TABLE "audio_files" ADD CONSTRAINT "FK_4d256e74fdf7dfc7fe3db8646d4" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audio_files" ADD CONSTRAINT "FK_65545b07c020cbdbbb7681608c2" FOREIGN KEY ("peak_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_80c457bc2a7f83aa7a38f07abcc" FOREIGN KEY ("metadata_language_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_5139ae6a60c799552ba18c91c68" FOREIGN KEY ("recording_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_7ca6e761a24b38013ad38713aa5" FOREIGN KEY ("audio_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_925cc591b88a93fc66156432dec" FOREIGN KEY ("metadata_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_localize" ADD CONSTRAINT "FK_2a1ac178b973083122b1d4d2f39" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ADD CONSTRAINT "FK_17a45017ebe3e6d8927e89067b8" FOREIGN KEY ("currency_id") REFERENCES "currencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_5bf30c50d712bae277ca356acea" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_contributors" ADD CONSTRAINT "FK_97b106f98cb47ae955d8866cb7f" FOREIGN KEY ("artist_role_id") REFERENCES "artist_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_action" ADD CONSTRAINT "FK_3605a7ccb2c31283c2f438d42d6" FOREIGN KEY ("action_id") REFERENCES "actions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_policy" ADD CONSTRAINT "FK_d75145347d0d7237e7b3ada91e9" FOREIGN KEY ("action_id") REFERENCES "actions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_e55f9cec9169401256cd9f07b60" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_233b4896b79bc3a09fe2e7cd33e" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_22d6e3e276290bd8aba903d0e28" FOREIGN KEY ("track_type_id") REFERENCES "track_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_bfba46e5d7c2ebed72f137ece6f" FOREIGN KEY ("track_origin_type_id") REFERENCES "track_origin_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_0693a1a86145ed3e897ebe2f407" FOREIGN KEY ("price_tier_id") REFERENCES "price_tiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_45af201b468843adc0043376602" FOREIGN KEY ("track_sensitive_id") REFERENCES "track_sensitives"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_861431344e4be139790d9e4aac4" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_9534d65dd5c6bf747bf5ce7d0aa" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_1a821992044479ed14974c1aaca" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_f569348fea9ac58ad1013e763a3" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_artist" ADD CONSTRAINT "FK_1d817cf036975de7f3bbfecae31" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_fa651daf7ef8e110e11a36df797" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_685eabfd94dcce03a30345f458e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ADD CONSTRAINT "FK_2dfa99602df7a4afba91716dd8b" FOREIGN KEY ("artist_role_id") REFERENCES "artist_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ADD CONSTRAINT "FK_f70e699e006d0dfa5b4c92562b1" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ADD CONSTRAINT "FK_67b825654a61e772db54cd3ae30" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ADD CONSTRAINT "FK_3a6a2583bb9d384c77d45aab213" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" ADD CONSTRAINT "FK_d5113bb1940e63d7cdeb9bae61b" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_territories" ADD CONSTRAINT "FK_513f1ce32ea2c51d0630869efbd" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_5508f9fce2612d730d956fb8f19" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_ff54e283e446c9cc70110512028" FOREIGN KEY ("release_timezone_id") REFERENCES "timezones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_98f690758f195a09664c15bae27" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_localize" ADD CONSTRAINT "FK_ee18fb83969889a91ce89fa1ae1" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_localize" ADD CONSTRAINT "FK_a21be0af831df856191968f2aec" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_460ef864795eb1672e48089c354" FOREIGN KEY ("metadata_language_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_f1c716d09fb61384da50e0b33fe" FOREIGN KEY ("audio_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_200409e6c7f867e159e2fb55bac" FOREIGN KEY ("metadata_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_90744b146ead957272664ad340a" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_c14b165d66f89b256290ca482c6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_84fc2bd2d4fc89e5a8585be1818" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_7788db4a1a36cc35260f185b20c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_047b7db2840104d32fdf49c14d9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" ADD CONSTRAINT "FK_fc14ecc0354329d0dabef1d337d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_6a47d535420458cb4e3e9cace59" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_b4634db530af2d532e8c028f94e" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_08a38106bfe4de059e116ef5158" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_18828d31d8180ad73610dd9de9a" FOREIGN KEY ("issue_level_id") REFERENCES "issue_level"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_007676689ebd5d5eca653c05d13" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_3ba5b99092625b7108b691b9bd1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_3ccfc197769ff601f52ea2d81a7" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_df81a19c7525b652c7badd3764c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_d7e987969e72adacb877570995d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_1b229bcb849cee7d07a3d127683" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_efba90c155ec02ae586fb7ed31d" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_bb2a90ed37750405dd793f3d7ff" FOREIGN KEY ("parent_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_43d8e67e7e017c92f243e92f21e" FOREIGN KEY ("tenant_tier_id") REFERENCES "tenant_tiers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_3fcaa9dbb974f9b1fdccc196926" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_1ed4230ec7b7ca4041402df9b59" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_f06a5757cf435fd81c0730e5778" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_eebaffddb3c6e049fa709e7de02" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4fa3646aeebcfb0cd9419dcec9d" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0df30683d0f67875fb6a610a01e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_45a949df1819b8e0040aace0ed1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_6882fa38fefa198de81b286342f" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_2848b2477636440af4de2858045" FOREIGN KEY ("news_post_id") REFERENCES "news_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_7528099678299bda1214e4581d7" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_0fae20a96808b8847db8d46935b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_e09fc99c2c4f0a1e6f5bbdfd0a8" FOREIGN KEY ("news_category_id") REFERENCES "news_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "file_node" ADD CONSTRAINT "FK_b166ac92d5e06acd0e769242e1a" FOREIGN KEY ("parent_id") REFERENCES "file_node"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_c3858ff058f009666f469464fc9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ADD CONSTRAINT "FK_04ccdbab2a9b025e4eab834b2c9" FOREIGN KEY ("aggregator_id") REFERENCES "aggregators"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ADD CONSTRAINT "FK_3f1bd64741fa999af4bda1e5498" FOREIGN KEY ("sftp_config_id") REFERENCES "sftp_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ADD CONSTRAINT "FK_ba1bbac7f0863173f40863e272c" FOREIGN KEY ("aggregator_id") REFERENCES "aggregators"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" ADD CONSTRAINT "FK_c921bcd2b55a7bd206a8b4845df" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" ADD CONSTRAINT "FK_62d261b9ed07a51e7fa59c472a9" FOREIGN KEY ("id_ancestor") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" ADD CONSTRAINT "FK_56255bf923a734bf9d9dff70430" FOREIGN KEY ("id_descendant") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tenants_closure" DROP CONSTRAINT "FK_56255bf923a734bf9d9dff70430"`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" DROP CONSTRAINT "FK_62d261b9ed07a51e7fa59c472a9"`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" DROP CONSTRAINT "FK_c921bcd2b55a7bd206a8b4845df"`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" DROP CONSTRAINT "FK_ba1bbac7f0863173f40863e272c"`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" DROP CONSTRAINT "FK_3f1bd64741fa999af4bda1e5498"`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" DROP CONSTRAINT "FK_04ccdbab2a9b025e4eab834b2c9"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_c3858ff058f009666f469464fc9"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4"`);
        await queryRunner.query(`ALTER TABLE "file_node" DROP CONSTRAINT "FK_b166ac92d5e06acd0e769242e1a"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_e09fc99c2c4f0a1e6f5bbdfd0a8"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_0fae20a96808b8847db8d46935b"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_7528099678299bda1214e4581d7"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_2848b2477636440af4de2858045"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_6882fa38fefa198de81b286342f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_45a949df1819b8e0040aace0ed1"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf"`);
        await queryRunner.query(`ALTER TABLE "role_permission" DROP CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0df30683d0f67875fb6a610a01e"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_4fa3646aeebcfb0cd9419dcec9d"`);
        await queryRunner.query(`ALTER TABLE "users" DROP CONSTRAINT "FK_eebaffddb3c6e049fa709e7de02"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_f06a5757cf435fd81c0730e5778"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_1ed4230ec7b7ca4041402df9b59"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_3fcaa9dbb974f9b1fdccc196926"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_43d8e67e7e017c92f243e92f21e"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_bb2a90ed37750405dd793f3d7ff"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_efba90c155ec02ae586fb7ed31d"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_1b229bcb849cee7d07a3d127683"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_d7e987969e72adacb877570995d"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_df81a19c7525b652c7badd3764c"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_3ccfc197769ff601f52ea2d81a7"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_3ba5b99092625b7108b691b9bd1"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_007676689ebd5d5eca653c05d13"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_18828d31d8180ad73610dd9de9a"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_08a38106bfe4de059e116ef5158"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_b4634db530af2d532e8c028f94e"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_6a47d535420458cb4e3e9cace59"`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" DROP CONSTRAINT "FK_fc14ecc0354329d0dabef1d337d"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_047b7db2840104d32fdf49c14d9"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_7788db4a1a36cc35260f185b20c"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_84fc2bd2d4fc89e5a8585be1818"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_c14b165d66f89b256290ca482c6"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_90744b146ead957272664ad340a"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_200409e6c7f867e159e2fb55bac"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_f1c716d09fb61384da50e0b33fe"`);
        await queryRunner.query(`ALTER TABLE "release_language" DROP CONSTRAINT "FK_460ef864795eb1672e48089c354"`);
        await queryRunner.query(`ALTER TABLE "release_localize" DROP CONSTRAINT "FK_a21be0af831df856191968f2aec"`);
        await queryRunner.query(`ALTER TABLE "release_localize" DROP CONSTRAINT "FK_ee18fb83969889a91ce89fa1ae1"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_98f690758f195a09664c15bae27"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_ff54e283e446c9cc70110512028"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_5508f9fce2612d730d956fb8f19"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a"`);
        await queryRunner.query(`ALTER TABLE "release_territories" DROP CONSTRAINT "FK_513f1ce32ea2c51d0630869efbd"`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" DROP CONSTRAINT "FK_d5113bb1940e63d7cdeb9bae61b"`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" DROP CONSTRAINT "FK_3a6a2583bb9d384c77d45aab213"`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" DROP CONSTRAINT "FK_67b825654a61e772db54cd3ae30"`);
        await queryRunner.query(`ALTER TABLE "release_contributors" DROP CONSTRAINT "FK_f70e699e006d0dfa5b4c92562b1"`);
        await queryRunner.query(`ALTER TABLE "release_contributors" DROP CONSTRAINT "FK_2dfa99602df7a4afba91716dd8b"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_685eabfd94dcce03a30345f458e"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_fa651daf7ef8e110e11a36df797"`);
        await queryRunner.query(`ALTER TABLE "release_artist" DROP CONSTRAINT "FK_1d817cf036975de7f3bbfecae31"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_f569348fea9ac58ad1013e763a3"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_1a821992044479ed14974c1aaca"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_9534d65dd5c6bf747bf5ce7d0aa"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_861431344e4be139790d9e4aac4"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_45af201b468843adc0043376602"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_0693a1a86145ed3e897ebe2f407"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_bfba46e5d7c2ebed72f137ece6f"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_22d6e3e276290bd8aba903d0e28"`);
        await queryRunner.query(`ALTER TABLE "tracks" DROP CONSTRAINT "FK_233b4896b79bc3a09fe2e7cd33e"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_e55f9cec9169401256cd9f07b60"`);
        await queryRunner.query(`ALTER TABLE "track_policy" DROP CONSTRAINT "FK_d75145347d0d7237e7b3ada91e9"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5"`);
        await queryRunner.query(`ALTER TABLE "dsp_action" DROP CONSTRAINT "FK_3605a7ccb2c31283c2f438d42d6"`);
        await queryRunner.query(`ALTER TABLE "track_contributors" DROP CONSTRAINT "FK_97b106f98cb47ae955d8866cb7f"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_5bf30c50d712bae277ca356acea"`);
        await queryRunner.query(`ALTER TABLE "price_tiers" DROP CONSTRAINT "FK_17a45017ebe3e6d8927e89067b8"`);
        await queryRunner.query(`ALTER TABLE "track_localize" DROP CONSTRAINT "FK_2a1ac178b973083122b1d4d2f39"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_925cc591b88a93fc66156432dec"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_7ca6e761a24b38013ad38713aa5"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_5139ae6a60c799552ba18c91c68"`);
        await queryRunner.query(`ALTER TABLE "track_language" DROP CONSTRAINT "FK_80c457bc2a7f83aa7a38f07abcc"`);
        await queryRunner.query(`ALTER TABLE "audio_files" DROP CONSTRAINT "FK_65545b07c020cbdbbb7681608c2"`);
        await queryRunner.query(`ALTER TABLE "audio_files" DROP CONSTRAINT "FK_4d256e74fdf7dfc7fe3db8646d4"`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ADD CONSTRAINT "FK_3f1bd64741fa999af4bda1e5498" FOREIGN KEY ("sftp_config_id") REFERENCES "sftp_configs"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ADD CONSTRAINT "FK_ba1bbac7f0863173f40863e272c" FOREIGN KEY ("aggregator_id") REFERENCES "aggregators"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ADD CONSTRAINT "FK_04ccdbab2a9b025e4eab834b2c9" FOREIGN KEY ("aggregator_id") REFERENCES "aggregators"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "app_config" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "app_config" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "batch_import_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "batch_import_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "backups" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "backups" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "file_node" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "file_node" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "file_node" ADD CONSTRAINT "FK_b166ac92d5e06acd0e769242e1a" FOREIGN KEY ("parent_id") REFERENCES "file_node"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_2848b2477636440af4de2858045" FOREIGN KEY ("news_post_id") REFERENCES "news_posts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_e09fc99c2c4f0a1e6f5bbdfd0a8" FOREIGN KEY ("news_category_id") REFERENCES "news_categories"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery_logs" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery_logs" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_32a6fc2fcb019d8e3a8ace0f55f" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_3d0a7155eafd75ddba5a7013368" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permission" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "role_permission" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "role_permission" ADD CONSTRAINT "FK_e3a3ba47b7ca00fd23be4ebd6cf" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "users" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_4fa3646aeebcfb0cd9419dcec9d" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "users" ADD CONSTRAINT "FK_eebaffddb3c6e049fa709e7de02" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_6882fa38fefa198de81b286342f" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_d0e5815877f7395a198a4cb0a46" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_e55f9cec9169401256cd9f07b60" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_c3858ff058f009666f469464fc9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_efba90c155ec02ae586fb7ed31d" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_1b229bcb849cee7d07a3d127683" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_d7e987969e72adacb877570995d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_f06a5757cf435fd81c0730e5778" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_1ed4230ec7b7ca4041402df9b59" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_df81a19c7525b652c7badd3764c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_007676689ebd5d5eca653c05d13" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_5508f9fce2612d730d956fb8f19" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0df30683d0f67875fb6a610a01e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_0fae20a96808b8847db8d46935b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_7528099678299bda1214e4581d7" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_f569348fea9ac58ad1013e763a3" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_1a821992044479ed14974c1aaca" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_08a38106bfe4de059e116ef5158" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_b4634db530af2d532e8c028f94e" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_6a47d535420458cb4e3e9cace59" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_861431344e4be139790d9e4aac4" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_047b7db2840104d32fdf49c14d9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_7788db4a1a36cc35260f185b20c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_c14b165d66f89b256290ca482c6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_5bf30c50d712bae277ca356acea" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_685eabfd94dcce03a30345f458e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_fa651daf7ef8e110e11a36df797" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_45a949df1819b8e0040aace0ed1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" ADD CONSTRAINT "FK_56255bf923a734bf9d9dff70430" FOREIGN KEY ("id_descendant") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants_closure" ADD CONSTRAINT "FK_62d261b9ed07a51e7fa59c472a9" FOREIGN KEY ("id_ancestor") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_bb2a90ed37750405dd793f3d7ff" FOREIGN KEY ("parent_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_3fcaa9dbb974f9b1fdccc196926" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_3ba5b99092625b7108b691b9bd1" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" ADD CONSTRAINT "FK_fc14ecc0354329d0dabef1d337d" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_98f690758f195a09664c15bae27" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_9534d65dd5c6bf747bf5ce7d0aa" FOREIGN KEY ("tenant_id") REFERENCES "tenants"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_43d8e67e7e017c92f243e92f21e" FOREIGN KEY ("tenant_tier_id") REFERENCES "tenant_tiers"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_3ccfc197769ff601f52ea2d81a7" FOREIGN KEY ("issue_id") REFERENCES "issues"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_18828d31d8180ad73610dd9de9a" FOREIGN KEY ("issue_level_id") REFERENCES "issue_level"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_dsp" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "countries" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "countries" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_5139ae6a60c799552ba18c91c68" FOREIGN KEY ("recording_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_80c457bc2a7f83aa7a38f07abcc" FOREIGN KEY ("metadata_language_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_460ef864795eb1672e48089c354" FOREIGN KEY ("metadata_language_country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_84fc2bd2d4fc89e5a8585be1818" FOREIGN KEY ("country_id") REFERENCES "countries"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_language" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "languages" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_localize" ADD CONSTRAINT "FK_2a1ac178b973083122b1d4d2f39" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_925cc591b88a93fc66156432dec" FOREIGN KEY ("metadata_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_language" ADD CONSTRAINT "FK_7ca6e761a24b38013ad38713aa5" FOREIGN KEY ("audio_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_200409e6c7f867e159e2fb55bac" FOREIGN KEY ("metadata_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_f1c716d09fb61384da50e0b33fe" FOREIGN KEY ("audio_language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_localize" ADD CONSTRAINT "FK_ee18fb83969889a91ce89fa1ae1" FOREIGN KEY ("language_id") REFERENCES "languages"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_localize" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_localize" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "distribution_ci_history" ADD CONSTRAINT "FK_c921bcd2b55a7bd206a8b4845df" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_233b4896b79bc3a09fe2e7cd33e" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_territories" ADD CONSTRAINT "FK_513f1ce32ea2c51d0630869efbd" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_language" ADD CONSTRAINT "FK_90744b146ead957272664ad340a" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" ADD CONSTRAINT "FK_d5113bb1940e63d7cdeb9bae61b" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ADD CONSTRAINT "FK_3a6a2583bb9d384c77d45aab213" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ADD CONSTRAINT "FK_f70e699e006d0dfa5b4c92562b1" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_artist" ADD CONSTRAINT "FK_1d817cf036975de7f3bbfecae31" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_localize" ADD CONSTRAINT "FK_a21be0af831df856191968f2aec" FOREIGN KEY ("release_id") REFERENCES "releases"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timezones" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "timezones" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_ff54e283e446c9cc70110512028" FOREIGN KEY ("release_timezone_id") REFERENCES "timezones"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_territories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_territories" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_dsp_delivery" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "release_artist" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "release_artist" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_22d6e3e276290bd8aba903d0e28" FOREIGN KEY ("track_type_id") REFERENCES "track_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_45af201b468843adc0043376602" FOREIGN KEY ("track_sensitive_id") REFERENCES "track_sensitives"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_policy" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_policy" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_policy" ADD CONSTRAINT "FK_d75145347d0d7237e7b3ada91e9" FOREIGN KEY ("action_id") REFERENCES "actions"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_action" ADD CONSTRAINT "FK_3605a7ccb2c31283c2f438d42d6" FOREIGN KEY ("action_id") REFERENCES "actions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_action" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsp_action" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_bfba46e5d7c2ebed72f137ece6f" FOREIGN KEY ("track_origin_type_id") REFERENCES "track_origin_types"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_contributors" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_contributors" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_contributors" ADD CONSTRAINT "FK_97b106f98cb47ae955d8866cb7f" FOREIGN KEY ("artist_role_id") REFERENCES "artist_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "release_contributors" ADD CONSTRAINT "FK_2dfa99602df7a4afba91716dd8b" FOREIGN KEY ("artist_role_id") REFERENCES "artist_roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "tracks" ADD CONSTRAINT "FK_0693a1a86145ed3e897ebe2f407" FOREIGN KEY ("price_tier_id") REFERENCES "price_tiers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ADD CONSTRAINT "FK_17a45017ebe3e6d8927e89067b8" FOREIGN KEY ("currency_id") REFERENCES "currencies"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_histories" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_scan_histories" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_localize" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_localize" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_language" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_language" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "track_artist" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_artist" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "audio_files" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "audio_files" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "files" ALTER COLUMN "id" SET DEFAULT uuid_generate_v4()`);
        await queryRunner.query(`ALTER TABLE "release_cover_art" ADD CONSTRAINT "FK_67b825654a61e772db54cd3ae30" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audio_files" ADD CONSTRAINT "FK_65545b07c020cbdbbb7681608c2" FOREIGN KEY ("peak_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audio_files" ADD CONSTRAINT "FK_4d256e74fdf7dfc7fe3db8646d4" FOREIGN KEY ("file_id") REFERENCES "files"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`COMMENT ON COLUMN "releases"."release_original_date" IS 'Ngày phát hành gốc Nullable when status is draft'`);
        await queryRunner.query(`ALTER TABLE "releases" DROP COLUMN "release_original_date"`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD "max_track_count" integer NOT NULL`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD "min_track_count" integer NOT NULL`);
        await queryRunner.query(`CREATE TYPE "public"."files_storage_provider_enum" AS ENUM('gcs', 'r2')`);
        await queryRunner.query(`ALTER TABLE "files" ADD "storage_provider" "public"."files_storage_provider_enum" NOT NULL DEFAULT 'gcs'`);
    }

}
