import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1776495022973 implements MigrationInterface {
    name = 'Migration1776495022973'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_f06a5757cf435fd81c0730e5778"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_5bf30c50d712bae277ca356acea"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6"`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_e55f9cec9169401256cd9f07b60"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_861431344e4be139790d9e4aac4"`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_1a821992044479ed14974c1aaca"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_f569348fea9ac58ad1013e763a3"`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_fa651daf7ef8e110e11a36df797"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_685eabfd94dcce03a30345f458e"`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_5508f9fce2612d730d956fb8f19"`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_c14b165d66f89b256290ca482c6"`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_7788db4a1a36cc35260f185b20c"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_047b7db2840104d32fdf49c14d9"`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_6a47d535420458cb4e3e9cace59"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb"`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_b4634db530af2d532e8c028f94e"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_08a38106bfe4de059e116ef5158"`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_007676689ebd5d5eca653c05d13"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_df81a19c7525b652c7badd3764c"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_d7e987969e72adacb877570995d"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_1b229bcb849cee7d07a3d127683"`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0df30683d0f67875fb6a610a01e"`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_6882fa38fefa198de81b286342f"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b"`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_7528099678299bda1214e4581d7"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_0fae20a96808b8847db8d46935b"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a"`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_c3858ff058f009666f469464fc9"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "creator_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "creator_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "modifier_id" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "modifier_id" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_f06a5757cf435fd81c0730e5778" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_5bf30c50d712bae277ca356acea" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_e55f9cec9169401256cd9f07b60" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_861431344e4be139790d9e4aac4" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_1a821992044479ed14974c1aaca" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_f569348fea9ac58ad1013e763a3" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_fa651daf7ef8e110e11a36df797" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_685eabfd94dcce03a30345f458e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_5508f9fce2612d730d956fb8f19" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_c14b165d66f89b256290ca482c6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_7788db4a1a36cc35260f185b20c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_047b7db2840104d32fdf49c14d9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_6a47d535420458cb4e3e9cace59" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_b4634db530af2d532e8c028f94e" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_08a38106bfe4de059e116ef5158" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_007676689ebd5d5eca653c05d13" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_df81a19c7525b652c7badd3764c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_d7e987969e72adacb877570995d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_1b229bcb849cee7d07a3d127683" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0df30683d0f67875fb6a610a01e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_6882fa38fefa198de81b286342f" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_7528099678299bda1214e4581d7" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_0fae20a96808b8847db8d46935b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_c3858ff058f009666f469464fc9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_c3858ff058f009666f469464fc9"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" DROP CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a"`);
        await queryRunner.query(`ALTER TABLE "news_posts" DROP CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_0fae20a96808b8847db8d46935b"`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" DROP CONSTRAINT "FK_7528099678299bda1214e4581d7"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b"`);
        await queryRunner.query(`ALTER TABLE "user_role" DROP CONSTRAINT "FK_6882fa38fefa198de81b286342f"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_0df30683d0f67875fb6a610a01e"`);
        await queryRunner.query(`ALTER TABLE "permissions" DROP CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_1b229bcb849cee7d07a3d127683"`);
        await queryRunner.query(`ALTER TABLE "tenants" DROP CONSTRAINT "FK_d7e987969e72adacb877570995d"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6"`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" DROP CONSTRAINT "FK_df81a19c7525b652c7badd3764c"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_007676689ebd5d5eca653c05d13"`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" DROP CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_08a38106bfe4de059e116ef5158"`);
        await queryRunner.query(`ALTER TABLE "issues" DROP CONSTRAINT "FK_b4634db530af2d532e8c028f94e"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb"`);
        await queryRunner.query(`ALTER TABLE "issue_level" DROP CONSTRAINT "FK_6a47d535420458cb4e3e9cace59"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_047b7db2840104d32fdf49c14d9"`);
        await queryRunner.query(`ALTER TABLE "dsps" DROP CONSTRAINT "FK_7788db4a1a36cc35260f185b20c"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716"`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" DROP CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_c14b165d66f89b256290ca482c6"`);
        await queryRunner.query(`ALTER TABLE "artists" DROP CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_5508f9fce2612d730d956fb8f19"`);
        await queryRunner.query(`ALTER TABLE "releases" DROP CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_685eabfd94dcce03a30345f458e"`);
        await queryRunner.query(`ALTER TABLE "album_formats" DROP CONSTRAINT "FK_fa651daf7ef8e110e11a36df797"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_f569348fea9ac58ad1013e763a3"`);
        await queryRunner.query(`ALTER TABLE "labels" DROP CONSTRAINT "FK_1a821992044479ed14974c1aaca"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_861431344e4be139790d9e4aac4"`);
        await queryRunner.query(`ALTER TABLE "genres" DROP CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a"`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" DROP CONSTRAINT "FK_e55f9cec9169401256cd9f07b60"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6"`);
        await queryRunner.query(`ALTER TABLE "actions" DROP CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1"`);
        await queryRunner.query(`ALTER TABLE "artist_roles" DROP CONSTRAINT "FK_5bf30c50d712bae277ca356acea"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_f06a5757cf435fd81c0730e5778"`);
        await queryRunner.query(`ALTER TABLE "tenant_user" DROP CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2"`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_c3858ff058f009666f469464fc9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_scan_status" ADD CONSTRAINT "FK_85dae0cff6123b7f2a6438f60d4" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "news_posts" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_fe147445c9183558f0ae9d94e4a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts" ADD CONSTRAINT "FK_6c8759b16bcfb042ae2a733a31d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_0fae20a96808b8847db8d46935b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_posts_translation" ADD CONSTRAINT "FK_7528099678299bda1214e4581d7" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "news_categories" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "user_role" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_ca8de6216665737e9ed07b7dd1b" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_role" ADD CONSTRAINT "FK_6882fa38fefa198de81b286342f" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "roles" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "permissions" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_0df30683d0f67875fb6a610a01e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "permissions" ADD CONSTRAINT "FK_ef7f7e021a4d2c1ed99b191e849" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenants" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_1b229bcb849cee7d07a3d127683" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenants" ADD CONSTRAINT "FK_d7e987969e72adacb877570995d" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_e3bd0ca12141fc4d164cd43e1a6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_tiers" ADD CONSTRAINT "FK_df81a19c7525b652c7badd3764c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_007676689ebd5d5eca653c05d13" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_issue" ADD CONSTRAINT "FK_c8ebf2b66840fd0091619b8b7c6" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "issues" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_08a38106bfe4de059e116ef5158" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issues" ADD CONSTRAINT "FK_b4634db530af2d532e8c028f94e" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "issue_level" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_458cd1b2ec17842bb6ab78872bb" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "issue_level" ADD CONSTRAINT "FK_6a47d535420458cb4e3e9cace59" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "dsps" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_047b7db2840104d32fdf49c14d9" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsps" ADD CONSTRAINT "FK_7788db4a1a36cc35260f185b20c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "dsp_routing_configs" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "aggregators" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "sftp_configs" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_cddc892e6fbf2786ba7273ee716" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_profiles" ADD CONSTRAINT "FK_e378c55296b8e6f89d4b5dd721c" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "artists" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_c14b165d66f89b256290ca482c6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artists" ADD CONSTRAINT "FK_e4a5a92f3004f5420a95501ce26" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "releases" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_5508f9fce2612d730d956fb8f19" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "releases" ADD CONSTRAINT "FK_411fef0afd9eba8e63d05dbb20a" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "album_formats" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_685eabfd94dcce03a30345f458e" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "album_formats" ADD CONSTRAINT "FK_fa651daf7ef8e110e11a36df797" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "labels" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_f569348fea9ac58ad1013e763a3" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "labels" ADD CONSTRAINT "FK_1a821992044479ed14974c1aaca" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "genres" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_861431344e4be139790d9e4aac4" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "genres" ADD CONSTRAINT "FK_d13bb8a685f86748ee57299f7ef" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_types" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_5cca1e3fa45143c89b30314d89a" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_sensitives" ADD CONSTRAINT "FK_e55f9cec9169401256cd9f07b60" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "actions" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c786fff755e8aea94c0ee73f3e6" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "actions" ADD CONSTRAINT "FK_c144f2feaab17622e5a5f2b6ee5" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "track_origin_types" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_ab41a604cb75dce9558c50fc4e1" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "artist_roles" ADD CONSTRAINT "FK_5bf30c50d712bae277ca356acea" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "price_tiers" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "currencies" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "modifier_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "modifier_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "creator_id" SET DEFAULT '3adcd1d1-fcaf-4495-9e54-0a8bd0ad09f2'`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ALTER COLUMN "creator_id" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_f06a5757cf435fd81c0730e5778" FOREIGN KEY ("modifier_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tenant_user" ADD CONSTRAINT "FK_81bce9f2446bc68e5e2efd423a2" FOREIGN KEY ("creator_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }
}
