export enum ExecutionStatus {
	QUEUED = 'QUEUED',
	RUNNING = 'RUNNING',
	AWAITING_ACTION = 'AWAITING_ACTION', // Required manual intervention
	PARTIALLY_COMPLETED = 'PARTIALLY_COMPLETED',
	COMPLETED = 'COMPLETED',
	FAILED = 'FAILED',
	CANCELLED = 'CANCELLED',
}

export enum ExecutionType {
	INITIAL_RELEASE = 'INITIAL_RELEASE',
	UPDATE = 'UPDATE',
	TAKEDOWN = 'TAKEDOWN',
	RETRY = 'RETRY',
}

export enum StepType {
	GENERATE_UPC = 'GENERATE_UPC',
	GENERATE_ISRC = 'GENERATE_ISRC',

	CREATE_METADATA_ERN = 'CREATE_METADATA_ERN',

	CREATE_METADATA_CI = 'CREATE_METADATA_CI',

	UPLOAD_SFTP_CI = 'UPLOAD_SFTP_CI',
	CREATE_DONE_FOLDER = 'CREATE_DONE_FOLDER',

	UPLOAD_SFTP = 'UPLOAD_SFTP',

	EXPORT_EXCEL = 'EXPORT_EXCEL', // Sinh file excel
	SEND_EMAIL_EXPORT = 'SEND_EMAIL_EXPORT', // Gửi email
	WAITING_EXPORT = 'WAITING_EXPORT', // Chờ Admin xuất và upload thủ công
	CLEANUP = 'CLEANUP',
}

export enum StepStatus {
	PENDING = 'PENDING',
	RUNNING = 'RUNNING',
	SUCCESS = 'SUCCESS',
	FAILED = 'FAILED',
	SKIPPED = 'SKIPPED',
	WAITING_ACTION = 'WAITING_ACTION',
	CANCELLED = 'CANCELLED',
}
