export enum DB_CONST {
	DEFAULT_ID_LENGTH = 36,
	LONG_ID_LENGTH = 36,
	SHORT_ID_LENGTH = 10,
}

export enum LENGTH_ID {
	// base entity
	BASE_DEFAULT = DB_CONST.DEFAULT_ID_LENGTH,
	BASE_SHORT = DB_CONST.SHORT_ID_LENGTH,
	BASE_LONG = DB_CONST.LONG_ID_LENGTH,

	// entities
	ARTIST_ROLE = DB_CONST.LONG_ID_LENGTH,
	ARTIST = DB_CONST.SHORT_ID_LENGTH,
	COUNTRY = DB_CONST.LONG_ID_LENGTH,
	DSP = DB_CONST.SHORT_ID_LENGTH,
	USER = DB_CONST.LONG_ID_LENGTH,
	RELEASE = DB_CONST.LONG_ID_LENGTH,
	RELEASE_ARTIST = DB_CONST.LONG_ID_LENGTH,
	RELEASE_LANGUAGE = DB_CONST.LONG_ID_LENGTH,
	RELEASE_LOCALIZE = DB_CONST.LONG_ID_LENGTH,
	GENRE = DB_CONST.SHORT_ID_LENGTH,
	TRACK = DB_CONST.SHORT_ID_LENGTH,
	TRACK_ARTIST = DB_CONST.LONG_ID_LENGTH,
	TRACK_LANGUAGE = DB_CONST.LONG_ID_LENGTH,
	TRACK_LOCALIZE = DB_CONST.LONG_ID_LENGTH,
	ORGANIZATION = DB_CONST.LONG_ID_LENGTH,
	LANGUAGE = DB_CONST.LONG_ID_LENGTH,
	LABEL = DB_CONST.SHORT_ID_LENGTH,
	PERMISSION = DB_CONST.LONG_ID_LENGTH,
}
