-- Seed role_permission by codes
-- Requires: unique constraint on (role_id, permission_id)
WITH map(role_code, permission_code) AS (
    VALUES
    -- Analytics
    ('analytics.viewer', 'analytics.read'),
    ('analytics.creator', 'analytics.read'),
    ('analytics.editor', 'analytics.read'),
    ('analytics.admin', 'analytics.read'),
    -- Artist
    ('artist.viewer', 'artist.read'),
    ('artist.creator', 'artist.read'),
    ('artist.creator', 'artist.create'),
    ('artist.editor', 'artist.read'),
    ('artist.editor', 'artist.create'),
    ('artist.editor', 'artist.update'),
    ('artist.admin', 'artist.read'),
    ('artist.admin', 'artist.create'),
    ('artist.admin', 'artist.update'),
    ('artist.admin', 'artist.delete'),
    -- Dashboard
    ('dashboard.viewer', 'dashboard.read'),
    ('dashboard.creator', 'dashboard.read'),
    ('dashboard.editor', 'dashboard.read'),
    ('dashboard.admin', 'dashboard.read'),
    -- DSP
    ('dsp.viewer', 'dsp.read'),
    ('dsp.creator', 'dsp.read'),
    ('dsp.creator', 'dsp.create'),
    ('dsp.editor', 'dsp.read'),
    ('dsp.editor', 'dsp.create'),
    ('dsp.editor', 'dsp.update'),
    ('dsp.editor', 'dsp.update.deals'),
    ('dsp.editor', 'dsp.update.policies'),
    ('dsp.admin', 'dsp.read'),
    ('dsp.admin', 'dsp.create'),
    ('dsp.admin', 'dsp.update'),
    ('dsp.admin', 'dsp.update.deals'),
    ('dsp.admin', 'dsp.update.policies'),
    ('dsp.admin', 'dsp.delete'),
    ('dsp.admin', 'dsp.configure_integration'),
    -- Issue
    ('issue.viewer', 'issue.read'),
    ('issue.creator', 'issue.read'),
    ('issue.creator', 'issue.create'),
    ('issue.editor', 'issue.read'),
    ('issue.editor', 'issue.create'),
    ('issue.editor', 'issue.update'),
    ('issue.admin', 'issue.read'),
    ('issue.admin', 'issue.create'),
    ('issue.admin', 'issue.update'),
    ('issue.admin', 'issue.delete'),
    -- Label
    ('label.viewer', 'label.read'),
    ('label.creator', 'label.read'),
    ('label.creator', 'label.create'),
    ('label.editor', 'label.read'),
    ('label.editor', 'label.create'),
    ('label.editor', 'label.update'),
    ('label.admin', 'label.read'),
    ('label.admin', 'label.create'),
    ('label.admin', 'label.update'),
    ('label.admin', 'label.delete'),
    -- Release
    ('release.viewer', 'release.read'),
    ('release.creator', 'release.read'),
    ('release.creator', 'release.create'),
    ('release.editor', 'release.read'),
    ('release.editor', 'release.create'),
    ('release.editor', 'release.update'),
    ('release.editor', 'release.review'),
    ('release.admin', 'release.read'),
    ('release.admin', 'release.create'),
    ('release.admin', 'release.update'),
    ('release.admin', 'release.review'),
    ('release.admin', 'release.take_down'),
    -- Revenue
    ('revenue.viewer', 'revenue.read'),
    ('revenue.creator', 'revenue.read'),
    ('revenue.editor', 'revenue.read'),
    ('revenue.admin', 'revenue.read'),
    -- Tenant Issue
    ('tenant_issue.viewer', 'tenant_issue.read'),
    ('tenant_issue.creator', 'tenant_issue.read'),
    ('tenant_issue.creator', 'tenant_issue.create'),
    ('tenant_issue.editor', 'tenant_issue.read'),
    ('tenant_issue.editor', 'tenant_issue.create'),
    ('tenant_issue.editor', 'tenant_issue.update'),
    ('tenant_issue.admin', 'tenant_issue.read'),
    ('tenant_issue.admin', 'tenant_issue.create'),
    ('tenant_issue.admin', 'tenant_issue.update'),
    ('tenant_issue.admin', 'tenant_issue.delete'),
    -- Tenant Tier
    ('tenant_tier.viewer', 'tenant_tier.read'),
    ('tenant_tier.creator', 'tenant_tier.read'),
    ('tenant_tier.creator', 'tenant_tier.create'),
    ('tenant_tier.editor', 'tenant_tier.read'),
    ('tenant_tier.editor', 'tenant_tier.create'),
    ('tenant_tier.editor', 'tenant_tier.update'),
    ('tenant_tier.admin', 'tenant_tier.read'),
    ('tenant_tier.admin', 'tenant_tier.create'),
    ('tenant_tier.admin', 'tenant_tier.update'),
    ('tenant_tier.admin', 'tenant_tier.delete'),
    -- Track
    ('track.viewer', 'track.read'),
    ('track.creator', 'track.read'),
    ('track.creator', 'track.scan'),
    ('track.editor', 'track.read'),
    ('track.editor', 'track.scan'),
    ('track.admin', 'track.read'),
    ('track.admin', 'track.scan'),
    -- User (granular)
    ('user.viewer', 'user.read'),
    ('user.creator', 'user.read'),
    ('user.creator', 'user.create'),
    ('user.creator', 'user.invite'),
    ('user.editor', 'user.read'),
    ('user.editor', 'user.create'),
    ('user.editor', 'user.invite'),
    ('user.editor', 'user.update.info'),
    ('user.editor', 'user.update.status'),
    ('user.editor', 'user.update.role'),
    ('user.editor', 'user.update.tenant_type'),
    ('user.admin', 'user.read'),
    ('user.admin', 'user.create'),
    ('user.admin', 'user.invite'),
    ('user.admin', 'user.update.info'),
    ('user.admin', 'user.update.status'),
    ('user.admin', 'user.update.role'),
    ('user.admin', 'user.update.tenant_type'),
    ('user.admin', 'user.delete'),
    -- Workspace (granular)
    ('workspace.viewer', 'workspace.read'),
    ('workspace.creator', 'workspace.read'),
    ('workspace.creator', 'workspace.create'),
    ('workspace.editor', 'workspace.read'),
    ('workspace.editor', 'workspace.create'),
    ('workspace.editor', 'workspace.update.info'),
    ('workspace.editor', 'workspace.update.status'),
    ('workspace.admin', 'workspace.read'),
    ('workspace.admin', 'workspace.create'),
    ('workspace.admin', 'workspace.update.info'),
    ('workspace.admin', 'workspace.update.status'),
    ('workspace.admin', 'workspace.update.owner'),
    ('workspace.admin', 'workspace.update.config'),
    -- Role & Permission (management)
    ('user.editor', 'role.read'),
    ('user.editor', 'permission.read'),
    ('user.admin', 'role.read'),
    ('user.admin', 'permission.read')
)
INSERT INTO role_permission (role_id, permission_id)
SELECT r.id, p.id
FROM map m
JOIN roles r ON r.code = m.role_code
JOIN permissions p ON p.code = m.permission_code
ON CONFLICT DO NOTHING;